### ISSUE TITLE
Allow saving request response as example as part of collection request

### ISSUE THREAD

**Issue by himz** [usebruno/bruno#973] opened 2023-11-15 22:06 UTC
Allow saving request response as example as part of collection request. Currently feature provided is to download the response. Rather if we can save the request params and response - similar to postman, that will add lot of value.

**Comment by HNTQ** [comment] 2023-12-12 14:31
up. this is a really important feature for me.

**Comment by helloanoop** [comment] 2023-12-12 14:43
Until this feature lands, a temporary workaround is to store the responses in the `docs` section for reference

<img width="1398" alt="image" src="https://github.com/usebruno/bruno/assets/9350733/c141d48a-1782-4912-9b71-248bc21b9846">

**Comment by tlaloc911** [comment] 2024-02-28 19:33
Is possible to retreive the content of docs body via scripting?

**Comment by helloanoop** [comment] 2024-08-08 10:50
Closing this as this is a duplicate of #1235

**Closed by helloanoop** 2024-08-08 10:50 UTC
