### ISSUE TITLE
When configuring environments, cannot select any environment except the first

### ISSUE THREAD

**Issue by AlexKubiesa** [usebruno/bruno#2667] opened 2024-07-19 09:29 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

On the page for configuring environments (_environments dropdown > Configure_), whenever I try to select an environment other than the first one, the selection jumps back to the first environment.

I did not have this problem on Windows 10, but I noticed the problem recently when I started using Ubuntu 22.04.

### .bru file to reproduce the bug

[environments.zip](https://github.com/user-attachments/files/16310134/environments.zip)

### Screenshots/Live demo link

[Screencast from 07-19-2024 10:22:46 AM.webm](https://github.com/user-attachments/assets/185cbbbf-9740-4082-b883-73f2de54a712)

**Comment by sfreeman422** [comment] 2024-07-21 16:08
+1 seeing this on 1.21.0 using snap on ubuntu 22.04

**Comment by sfreeman422** [comment] 2024-07-21 16:16
Pulled down latest from source and _not_ seeing this issue. Wondering if a new release needs to go out on snap/apt/etc?

**Comment by sfreeman422** [comment] 2024-07-21 16:21
PR #2660 reverts PR #2640 which appears to resolve this issue... what's interesting is the #2640 was not a part of the most [recent release](https://github.com/usebruno/bruno/compare/v1.20.4...v1.21.0) per GitHub. 

@AlexKubiesa can you confirm if you are using the apt, .deb or snap version of Bruno? I am wondering if perhaps we are both using Snap and snap was released on a version that is not the version listed in GitHub?

**Comment by AlexKubiesa** [comment] 2024-07-21 23:11
Yes, I'm using the snap version of Bruno

**Comment by sanjai0py** [comment] 2024-07-22 06:48
Hey @AlexKubiesa, I apologize for the inconvenience caused by the bug. The snap build was triggered after the PR https://github.com/usebruno/bruno/pull/2660 was merged, which caused the bug. Although it has been reverted, the snap release had already been published. 

Therefore, please revert back to the version before `1.21.0` until the fix is released by the end of the day.

**Comment by sanjai0py** [comment] 2024-07-22 07:46
Hey @AlexKubiesa, the version '1.22.0' has been released early for Snap with a fix for the issue. The other Linux builds will follow. Thank you for your patience!

**Comment by AlexKubiesa** [comment] 2024-07-22 09:24
I have updated now and the bug is fixed. Thank you!

**Comment by sanjai0py** [comment] 2024-07-22 09:27
Closing this issue is marked as resolved. Thank you, @AlexKubiesa, for reporting this issue!

**Closed by sanjai0py** 2024-07-22 09:27 UTC
Labels: bug
