### ISSUE TITLE
Multiline graphql queries parse error

### ISSUE THREAD

**Issue by leealandennis** [usebruno/bruno#1399] opened 2024-01-16 18:48 UTC
Seems to be an issue in 1.6.1 where multiline queries are not supported unless you have "\n" everywhere it's needed.  Downgraded to 1.1.1 and it works.

Example query that works on 1.1.1 but not 1.6.1

1.6.1:
<img width="1319" alt="image" src="https://github.com/usebruno/bruno/assets/13697556/5fcb99d4-f55a-4f55-87e0-1e6a7d3a9131">

1.1.1 (didn't put full screenshot for data integrity)

<img width="856" alt="image" src="https://github.com/usebruno/bruno/assets/13697556/a1d588bd-8cd2-4efb-989e-c07e52bd8859">

Example of query that works on both:

<img width="856" alt="image" src="https://github.com/usebruno/bruno/assets/13697556/8575e144-6648-4388-846d-a8501562ed12">

**Comment by Its-treason** [comment] 2024-01-16 19:34
Seems to be related to #1321 and this PR: #1154

**Comment by sanjai0py** [comment] 2024-07-05 07:28
Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1)

**Closed by sanjai0py** 2024-07-05 07:28 UTC
