### ISSUE TITLE
I can't save request with "%" character in password.

### ISSUE THREAD

**Issue by lengeradam** [usebruno/bruno#1375] opened 2024-01-12 08:18 UTC
When I try to save the request with "%" character in password, it is not saved.

**Comment by dev-abir** [comment] 2024-01-20 19:15
Can you be more specific with details and steps to reproduce?

**Comment by lengeradam** [comment] 2024-01-21 12:36
Here are the steps:
1. Create request
2. Go to Auth
3. Choose "Basic Auth"
4. In the password field enter any string containing "%"
5. Click on Save (or Cmd+S)
6. Request is not saved

If I remove the "%" from the password, I'm able to save the request.

**Comment by dev-abir** [comment] 2024-01-21 16:47
Looks like some issue related to .bru to json conversion...

Related https://github.com/usebruno/bruno/issues/1076

**Comment by sanjai0py** [comment] 2024-07-05 06:55
Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1) 

https://github.com/usebruno/bruno/assets/84461672/6e4bda8b-0c26-4e4b-b7d3-6f5647295404

**Closed by sanjai0py** 2024-07-05 06:55 UTC
