### ISSUE TITLE
Bruno 1.19.0 says that it's version is 1.18.0 in "About Bruno" dialog (Help Menu)

### ISSUE THREAD

**Issue by derjohn** [usebruno/bruno#2526] opened 2024-06-28 11:04 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In the file packages/bruno-electron/package.json there is 1.18.0 hardcoded even in the 1.19.0. 
I think someone forgot bump the version number in the code before releasing. 

### Screenshots/Live demo link

.

**Comment by chrisnagel** [comment] 2024-07-04 15:02
@derjohn In the current version (e.g. v1.20.1), the expected version number is displayed in the About dialog. Can the problem be considered solved?

**Comment by pietrygamat** [comment] 2024-07-04 16:39
@chrisnagel It should not if you ask me. Compare the [history of this file](https://github.com/usebruno/bruno/commits/589e173256ffdab860c1bdf5868ca461b674f21e/packages/bruno-app/src/components/Sidebar/index.js) with [release history](https://github.com/usebruno/bruno/releases). What can be noticed is that the problem is recurring. There should be a global definition of version variable synced with `package.json`.

**Comment by derjohn** [comment] 2024-07-04 22:01
Well, at least I can say that my current bruno ( from nixpkgs / nixos ) says V.1.20.0. 
@pietrygamat Do you have an PR to solve this issue?

**Comment by pietrygamat** [comment] 2024-07-05 00:16
@derjohn that's not something I'd take up confidently, no. I can only hint at the gaps I see, like the aforementioned need for labourous manual edits in .js files for what should be stored only in project metadata, or lack of synchronization between package.json's of submodules (e.g. `bru-cli` is locked at 1.16.0, and that is how locally build version identifies itself on current main - which is basically the same problem). I can only assume the version released onto [npmjs](https://www.npmjs.com/package/@usebruno/cli) has correct version due to modifications comming from closed source code, so making a change in open sourced part only could potentially break stuff. 

On the other hand, perhaps it's out of scope for this bug or the closed source code/pipelines are now foolproof, and we won't be seeing problems like that again, right @sanjai0py  :smirk:?

**Comment by vayalildanie** [comment] 2024-08-15 23:14
This updating version count issue found under the help tab has now been fixed as of (v1.25)

**Closed** 2024-08-26 11:26 UTC
Labels: bug
