### ISSUE TITLE
Add color coding for environment

### ISSUE THREAD

**Issue by SZubarev** [usebruno/bruno#2703] opened 2024-07-25 19:09 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

It would be convenient to have an optional color attribute for each environment to color-code environment selected so user can see which environment they work with at this moment also by color of selection dropdown

### Mockups or Images of the feature

![env_dev](https://github.com/user-attachments/assets/e7405a24-a998-4d01-98ad-8981afd74fe5)
![env_prod](https://github.com/user-attachments/assets/cc4583fa-7b48-4b55-8d58-f065ae8b2415)

**Comment by Its-treason** [comment] 2024-07-25 21:57
Duplicate of #304

**Comment by sanjai0py** [comment] 2024-07-26 06:16
Closing this as duplicate of #304

**Closed by sanjai0py** 2024-07-26 06:16 UTC
Labels: enhancement
