### ISSUE TITLE
Search feature is completely brokenand JSON is not collapsible

### ISSUE THREAD

**Issue by Thexumaker** [usebruno/bruno#2644] opened 2024-07-16 01:19 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Prior to 1.20, command F would pop up a search bar

After 1.20, it no longer works. The JSON collapse arrows are also broken.

### Screenshots/Live demo link

Before: 
<img width="821" alt="Screenshot 2024-07-15 at 6 19 27 PM" src="https://github.com/user-attachments/assets/9a7eeb96-e5a4-4222-b3f6-b040839f58ad">

After: 
<img width="820" alt="Screenshot 2024-07-15 at 6 18 10 PM" src="https://github.com/user-attachments/assets/70b231cd-bcdf-44ce-a04e-369b0949bdca">

**Comment by sanjai0py** [comment] 2024-07-16 05:09
Duplicate of https://github.com/usebruno/bruno/issues/2580. Thank you for reporting the bug. Since a related issue tracking the bug already exists, you can add a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to issue https://github.com/usebruno/bruno/issues/2580 instead.

**Closed by sanjai0py** 2024-07-16 05:09 UTC
Labels: bug
