### ISSUE TITLE
Hello. Do you have any plan to implement cookies? i.e. set-cookies, cookies management, and automatically send the cookies under the same domain

### ISSUE THREAD

**Issue by BenjaminOmar** [usebruno/bruno#991] opened 2023-11-19 15:51 UTC
Hello. Do you have any plan to implement cookies? i.e. set-cookies, cookies management, and automatically send the cookies under the same domain

_Originally posted by @yjlcoder in https://github.com/usebruno/bruno/issues/119#issuecomment-1740304454_

is this planned? last thing needed for our team to migrate to bruno

**Comment by martinsefcik** [comment] 2023-11-19 20:52
See Version 2 in roadmap #384

Also issue #968 and PR with basic cookie support #969

**Comment by Tanja-4732** [comment] 2023-11-20 00:00
> See Version 2 in roadmap #384
> 
> Also issue #968 and PR with basic cookie support #969

@BenjaminOmar 

Well, as stated by @martinsefcik, I already implemented an (admittedly primitive) way of doing this in #969.

---

Furthermore, this is a duplicate of #968

**Comment by helloanoop** [comment] 2023-11-20 13:24
@BenjaminOmar Cookies are now supported in `v1.2.0` 🎉🎉

**Closed** 2023-11-21 10:30 UTC
