### ISSUE TITLE
Can't Move Request to New Folder

### ISSUE THREAD

**Issue by lukedegruchy** [usebruno/bruno#1387] opened 2024-01-15 14:12 UTC
# Steps to reproduce:

1. Create a folder
2. Create a request within that folder
3. Create a second folder
4. Attempt to move the request within the first folder to the second

# Expected results

* The request appears in the second folder

# Actual results

* The request stays in the first folder

# Additional context

* I reproduced this on the latest version of macOS with Bruno 1.6.1

**Comment by bpoulaindev** [comment] 2024-01-15 14:47
Can you provide a screen record of this behaviour ? I tried to reproduce but the requets did move to the 2nd folder.

**Comment by devsales** [comment] 2024-06-24 12:50
This works for me as well. But what I can't do is move a request in another collection. Is this a known limitation?

**Comment by sanjai0py** [comment] 2024-07-05 07:25
Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1)

**Closed by sanjai0py** 2024-07-05 07:25 UTC
