### ISSUE TITLE
It should be possible to see the number of the elements when searched in the response message

### ISSUE THREAD

**Issue by emirozmen07** [usebruno/bruno#2546] opened 2024-07-02 12:50 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

When we search in the response data section, being able to see the number of the elements that matches to the search would be great. Also we could see the index of the current element. Potentially, it can also be added to other sections of the app where we are able to search.

### Mockups or Images of the feature

![image](https://github.com/usebruno/bruno/assets/144101618/2af5e85d-7ca6-45c8-9be0-98f695b58a5e)

**Comment by sanjai0py** [comment] 2024-07-02 13:17
Duplicate of #1497

**Closed** 2024-08-02 05:51 UTC
Labels: enhancement
