### ISSUE TITLE
Got Error invoking remote method 'send-http-request': SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by ShinoharaHaruna** [usebruno/bruno#2079] opened 2024-04-15 03:40 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

As shown in the screenshot, when I tried to send a request to test a login rest API, the response in Bruno is an error. However, the request was actually successfully sent and a JWT token string should be in response.

The request has nothing but a JSON body.

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/8310292/f66d0400-9b82-45c3-a2e2-6c77589cfd35)

**Comment by dwiyatci** [comment] 2024-04-15 13:41
Got similar error in v1.13.0:
```
Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined
```

I tried to downgrade to v1.12.3, it didn't occur there.

**Comment by ShinoharaHaruna** [comment] 2024-04-16 05:37
> Got similar error in v1.13.0:
> 
> ```
> Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined
> ```
> 
> I tried to downgrade to v1.12.3, it didn't occur there.

Looks like it's still going to happen on v1.12.3

Besides, I've tried AppImage version and Deb version, and the issue is the same.

**Comment by pavan-world** [comment] 2024-04-17 04:10
> Got similar error in v1.13.0:
> 
> ```
> Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined
> ```
> 
> I tried to downgrade to v1.12.3, it didn't occur there.

https://github.com/usebruno/bruno/issues/2103

Are you seeing something like this?

**Comment by ClementValot** [comment] 2024-04-17 08:14
> Got similar error in v1.13.0:
> 
> ```
> Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined
> ```
> 
> I tried to downgrade to v1.12.3, it didn't occur there.

Got a similar regression upgrading from 1.12.3 to 1.13.1, firing some requests displays `ReferenceError` and triggers a dozen `AbortionError` in the console 
![image](https://github.com/usebruno/bruno/assets/65364056/632abc1c-c2b5-44d3-890b-b9f7922ed1b2)

I'll run a few tests to try and pinpoint which part of the request triggers these errors

**Comment by dwiyatci** [comment] 2024-04-17 12:40
@pavan-world @ClementValot I actually saw more like what Pavan saw in #2103. Just got a plain flat error in the Response panel after firing a request, without any other errors thrown in the console from any JS file.

![_Applications_Bruno app_Contents_Resources_app asar_web_index html](https://github.com/usebruno/bruno/assets/4405796/281d48bf-7247-48c9-ae5b-5dd38523f110)

Obviously I use `bru.setEnvVar` in the Pre Request script of my collection, but I believe it doesn't even get to that line of code yet. As of now, v1.13 is unusable for me, hence the downgrading to v1.12.

**Comment by pavan-world** [comment] 2024-04-17 15:35
I am on Mac and downgrading to 1.12.3 also giving same issue...
Do I need to clean-up any cache ?

**Comment by pavan-world** [comment] 2024-04-17 20:24
![image](https://github.com/usebruno/bruno/assets/3612079/aa81ea50-1af2-4e4d-9d09-bc6daaeb1b62)

I am able to run the same collection in both 1.12.3 and 1.13.1 same time **clearly 1.13.1 is throwing the error**

"Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined"

looks like the console error exists in both versions...

**Comment by pavan-world** [comment] 2024-04-17 22:06
with more testing, 

`bru.getEnvName()`

is causing error in 1.13.1

**Comment by dwiyatci** [comment] 2024-04-18 11:59
> with more testing,
> 
> `bru.getEnvName()`
> 
> is causing error in 1.13.1

Aw ye, I can confirm this! 😮

@pavan-world Would it make sense then to change the title of your issue #2103 to attract more attention, e.g. "**Calling `bru.getEnvName()` in collection's script threw `"Error invoking remote method 'send-http-request': ReferenceError: setEnvVar is not defined"`**", and update the description with your screenshot above (I don't think those errors you saw in the console are relevant tho)?

I just wonder why not so many are reporting this issue up till now 🤔

**Comment by pavan-world** [comment] 2024-04-19 19:07
looks like this issue is not resolved yet..!

**Comment by ClementValot** [comment] 2024-04-19 21:32
Let's let Anoop work his magic 😊

If you need a workaround in the meantime you can substitute `bru.getEnvName()` with `bru.envVariables.__name__`

**Comment by pavan-world** [comment] 2024-04-22 19:27
this issue is resolved with v1.14.0

**Comment by BoilingSoup** [comment] 2024-06-01 21:48
I tried snap package 1.18.0
and AppImage 1.18.1

They both run into this problem immediately

**Comment by BBlackwo** [comment] 2024-06-27 03:54
Getting this error on v1.19.0

**Comment by sanjai0py** [comment] 2024-07-10 10:06
This issue is being closed as resolved/stale. If the issue continues, please open a new one.

**Closed by sanjai0py** 2024-07-10 10:06 UTC
Labels: bug

**Comment by yilmazeren0** [comment] 2024-12-11 08:11
same error continue on last version. Post request is done with success but this error occur.
