### ISSUE TITLE
Variables don't work in Body Multipart Form

### ISSUE THREAD

**Issue by LCLLL** [usebruno/bruno#3050] opened 2024-09-09 04:06 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Variables don't work in Body Multipart Form

### Screenshots/Live demo link

<img width="888" alt="image" src="https://github.com/user-attachments/assets/866d6995-4e20-4072-af0c-5ed0a76308d8">
<img width="836" alt="image" src="https://github.com/user-attachments/assets/f59ff328-4681-488f-b98a-032de9e159d7">
<img width="807" alt="image" src="https://github.com/user-attachments/assets/288d11e9-1ded-4bcb-8567-e401650f5262">
<img width="440" alt="image" src="https://github.com/user-attachments/assets/0264fad6-0e3f-4dbb-b07e-5070e5d5a5a3">

**Comment by matthewb531** [comment] 2024-09-09 09:11
Unfortunately this is a duplicate of this old very annoying bug https://github.com/usebruno/bruno/issues/352 😩

**Comment by helloanoop** [comment] 2024-10-01 18:13
This has been fixed and is available in `v1.32.0` 🎉

**Closed by helloanoop** 2024-10-01 18:13 UTC
Labels: bug
