### ISSUE TITLE
[User Experience] Remember the base location of the Bruno collections 

### ISSUE THREAD

**Issue by premeaswaran** [usebruno/bruno#636] opened 2023-10-17 10:19 UTC
While creating/importing multiple collections, the user is expected to select the folder (location to save the bruno collection) every time which is slightly frustrating at times. However, most of the times, if not always, users tend to use the same location to save all their Bruno collections.

Can we make Bruno remember the last selected folder and use it as a base location by default. The user can change the location only if needed.

**Note:** I tried quickly looking for a relate issue and can't find any. Apologies if this is a duplicate.

**Comment by sanjai0py** [comment] 2024-07-01 11:10
Duplicate of #222

**Closed by sanjai0py** 2024-07-01 11:10 UTC
