### ISSUE TITLE
Post with application/x-www-form-urlencoded and TEXT body won't pick up environment variables.

### ISSUE THREAD

**Issue by mattisking** [usebruno/bruno#2400] opened 2024-05-31 20:54 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have a vendor API that returns tokens for us to use in non-prod environments. The API requires a POST using Content-Type = application/x-www-form-urlencoded and a Body of type TEXT. In the body, if I have something like orderId={{ORDER_ID}} when I post, It literally sends: orderId={{ORDER_ID}} without replacing ORDER_ID from the environment variables. If I remove the Content-Type header, it does replace ORDER_ID as expected: orderId=123456. Removing the Content-Type isn't an option for me as it's not my API.

### .bru file to reproduce the bug

meta {
  name: Demo
  type: http
  seq: 1
}

post {
  url: https://localhost:53245
  body: text
  auth: none
}

headers {
  ~Content-Type: application/x-www-form-urlencoded
}

body:text {
  orderId={{ORDER_ID}}
}

script:pre-request {
  var date = new Date();
  var time = date.getTime();
  bru.setEnvVar("ORDER_ID", time);
  
}

### Screenshots/Live demo link

Here's the request and result:
![image](https://github.com/usebruno/bruno/assets/412168/bce9d8ca-3f81-4c0f-9b52-3a71cc109a5b)

Here's a pic of the environment variables:
![image](https://github.com/usebruno/bruno/assets/412168/c3cc377b-d6fe-4314-8172-dd484b7b1773)

Note that the fact the URL is junk doesn't matter. You can see in the image on top that {{ORDER_ID}} isn't being substituted from the environment variables.

If I remove the Content-Type header you'll see that it does the replacement:
![image](https://github.com/usebruno/bruno/assets/412168/3585843a-183f-41ed-a190-d10043975fb1)

**Comment by jwetzell** [comment] 2024-06-21 12:23
@mattisking I am not able to replicate this in Bruno v1.19. Could you try and see if this issue has been resolved?

**Comment by StreetXHasu** [comment] 2024-06-21 18:50
same error. 1.19
windows 11
![image](https://github.com/usebruno/bruno/assets/69196228/1db3f5e5-aa3d-4afb-b68e-cf72c4f243b5)

**Comment by mattisking** [comment] 2024-06-21 20:28
Ok, so, when I started with Bruno to see the feasibility in moving our test suites over (cause I’m a fan), I imported my largest suite for one application that includes lots of nested folders, a ton of variables (with the intention of embracing your secure options for local developers).

The import was a plus and minus affair. It wasn’t all that consistent in recognizing tests vs post scripts and there were a number of scripts that weren’t converter over correctly. I don’t so much care about any of that though in the future I’ll do some bug reports.

I found that Bruno wasn’t able to pick up ANY of my variables initially and I actually reinstalled it a couple of times before it suddenly just worked. At that point I began properly migrating the tests. Until I hit this one. It will not read these variables out of the selected collection. And the test I uploaded which is still broken, as is the real version, I actually created in the same folder as the real one. I exported all that for this bug ticket.

if I recreate the same test in a NEW collection, it works. It doesn’t work in the existing collection I imported. I’m curious if the bug might have to do with nested sub folders. I’ll see if I can identify that.

**Comment by mattisking** [comment] 2024-06-21 20:51
Little more straight forward. Wasn't sure I could share some of this but these URL's are public. So based on these:
https://developerengine.fisglobal.com/apis/usecomm/eprotect/introduction/getting-started
https://developerengine.fisglobal.com/apis/usecomm/eprotect/integrating/testing-certification

[goofingaround.zip](https://github.com/user-attachments/files/15933570/goofingaround.zip)

Import this whole thing. I cleared out my company bits from it, but you don't need to make a successful call to test it. As long as you see the values get filled.

**Comment by jwetzell** [comment] 2024-06-21 21:04
Seems multipart form is the only body type not working as far as I can tell. [This file/section](https://github.com/usebruno/bruno/blob/fc626041e2ac1f551a4801b03b99e1935623e64a/packages/bruno-electron/src/ipc/network/interpolate-vars.js#L81) here is the culprit. Looks like bruno is using a pretty dated and not spec compliant library to get FormData in NodeJS. Without switching to something more spec compliant FormData implementation I don't know of way to solve this.

**Comment by kumpan-david** [comment] 2024-07-04 10:19
I managed to reproduce this in v1.20.0 by having a variable with backslash `\` in it's value.
This caused the JSON.parse to fail exactly in the spot @jwetzell pointed out, and because it has an empty catch-block the variable interpolation just gets ignored.
Usually NodeJS handles escaping of backslashes from the shell and so does dotenv, so I'm not sure where and why Bruno loads these variables.

**Comment by overmind1001** [comment] 2024-09-04 09:11
I was able to reproduce this in v1.27.0. When I include {{password}} Param in "Form URL Encoded" Body it stops substituting "{{password}}" and sends it as is. Password contains **double quote mark** '"'. If I remove double quote mark then parameter is substituted correctly.

**Comment by anusree-bruno** [comment] 2024-11-27 09:18
Tested in v1.35, variables are interpolated
![image](https://github.com/user-attachments/assets/1421e937-3e58-4e2a-ad35-a16f6cd69e68)

**Comment by fcmss** [comment] 2024-11-27 10:45
Awesome, thank you for the update!

**Comment by anusree-bruno** [comment] 2024-12-30 06:43
Closing this issue.

**Closed by anusree-bruno** 2024-12-30 06:43 UTC
Labels: bug, module-request, can-be-closed
