### ISSUE TITLE
Variable not extracted when using multipart/form

### ISSUE THREAD

**Issue by boy-oo** [usebruno/bruno#2727] opened 2024-07-31 03:27 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When using `multipart/form`, the variable that I've been set on environment is not extracted. I can see the value when I hover it, but the value that was received by the api is the variable name along with the curly bracket. The reason why I say the variable is not extracted is because I tried to dump the body in my api.

### Screenshots/Live demo link

https://github.com/user-attachments/assets/a1b7c581-d3ab-4403-8fd3-1935bf683954

**Comment by Its-treason** [comment] 2024-07-31 06:10
Duplicate of #352

**Comment by sanjai0py** [comment] 2024-08-02 06:33
Closing this as a duplicate of #352. 

The pull request addressing this issue includes some breaking changes in the application, so an alternative approach that avoids breaking changes was introduced. However, it requires thorough testing. We are prioritizing this. 

Please react with a 👍 to issue #352 and add a comment if possible.

**Closed by sanjai0py** 2024-08-02 06:33 UTC
Labels: bug
