### ISSUE TITLE
Feature: Add Request Examples

### ISSUE THREAD

**Issue by amr-hammoud** [usebruno/bruno#2237] opened 2024-05-04 11:21 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Sometimes I need to show my team members other ways to use the request, mainly through different body. This helps show what different responses this request might return

### Mockups or Images of the feature

N/A

**Comment by Its-treason** [comment] 2024-05-04 11:54
Duplicate of #885

**Closed** 2024-05-13 10:13 UTC
Labels: enhancement
