### ISSUE TITLE
Authorization type 'API Key' not supported in Bruno

### ISSUE THREAD

**Issue by AdithyaKRamesh** [usebruno/bruno#1655] opened 2024-02-23 11:11 UTC
Hi Team,

I decided to start using Bruno instead of Postman, and noticed this limitation in Bruno: API Key type authorization is not available at all.

This is a serious limitation for me.

Can you please support this type of authorization, for the API call.
Attaching the screenshot of the same that is supported in Postman, and also the version details of Bruno currently installed on my Macbook M1 Pro.

Looking forward to an early fix for this issue.

Thanks and best regards,
Adithya

**Comment by matt-fevold** [comment] 2024-02-23 19:58
looks like that feature is being tracked with #1005

**Comment by helloanoop** [comment] 2024-06-17 07:28
Closing this as it is a duplicate of #1005

**Closed by helloanoop** 2024-06-17 07:28 UTC
