### ISSUE TITLE
[BUG] Vars in request override the environment variables definitely

### ISSUE THREAD

**Issue by luc-freyermuth** [usebruno/bruno#1101] opened 2023-11-30 12:50 UTC
Hello, I am here to report a bug I found when starting to use bruno at work !

## Description of the issue

I create an environment variable, lets say `project_id` and set a value to the variable, for example `10`. I enable this environment and create a request that uses this env variable in its path. eg: `http://localhost:3000/projects/{{project_id}}/users`. When I run the request, everything works, the value `10` is reflected in the URL.

Then, I create a var of the same name in the Vars > Pre Request section. Lets says `project_id` with value `20`. When I send the request, now the value `20` is reflected in the URL as expected.

Then, I delete my Pre Request Variable and send the request again. **The value `20` is still reflected in the URL**. And the value will be reflected everywhere, even in other requests. This seems to indicate that the global state of the application has been affected by my request Vars. At this point, the only solution I found to reset my variable to its original value is to restart bruno completely.

## Expected behavior

As a user, I would expect that data specified in the Vars tab of one request should not affect the application global state, so that when I change requests or delete the Vars line, the behavior goes back to where it was before i created the Vars line.

## My 2 cents as a dev

I didn't take the time to take a look at bruno's source code, so I could be really wrong. This behavior gives the feeling that global state is used and modified while processing the request. This could become an issue in future developments, as it couples the action of sending the request with the use case (sending a request by clicking "send" in an item of a collection). This could make some future requests harder to implement (eg. creating a runner that sends multiple requests from a file) because you'll have to control and remember all the side effects to avoid unexpected behavior ! 

And thanks for all your work on bruno ! :)

**Comment by SoulKa** [comment] 2024-02-07 11:56
Duplicate of #1526

**Comment by epestela** [comment] 2024-02-07 12:18
I must agree that is a quite annoying issue. 
Encountered this quite fast tbh while testing out Bruno
because of the unexpected behaviors that this can create I think it's quite critical to address this

**Comment by SoulKa** [comment] 2024-02-07 15:32
Deactivating the vars now works as expected with the fix #1539. However, deleting still doesn't work!

**Comment by samuel-deal-tisseo** [comment] 2024-03-21 13:49
Maybe a proper solution is to use a different syntax for vars and env values.

But this would be a massive breaking change

**Closed** 2024-07-09 10:19 UTC
