### ISSUE TITLE
API / Collection Authorization

### ISSUE THREAD

**Issue by rsb-23** [usebruno/bruno#119] opened 2023-03-06 05:39 UTC
> This issue has been closed, If you'd like an auth method to be supported, please create a new issue

## Authorization

- [x] Basic Auth
- [x] Bearer Auth
- [x] Digest Auth
- [x] Cookie Auth - #968
- [x] AWS SigV4 Auth
- [x] OAuth 2.0 #1003
- [ ] OAuth 1.0 #1004
- [x] API Key based Auth #1005

If you'd like an auth method to be supported, please create a new issue

**Comment by helloanoop** [comment] 2023-03-06 12:50
Hi @rsb-23 

Supporting Auth is a huge priority, and I plan to have it developed and released within the next 10 days.
The api's I have mostly work on have api key based auth that is passed in the headers.

Planning to get a release out with these 2 Auths
1. Bearer Token Auth
2. API Key based auth (passed in headers/query params/cookies)

Is there a specific auth that you'd like us to prioritise to build ?

**Comment by rsb-23** [comment] 2023-03-06 13:12
These two are mostly used, hence this plan is perfect.

**Comment by faolitarna** [comment] 2023-05-31 07:48
Is OAuth 2.0 support planned? That's the only thing missing that stops us to move to Bruno.

**Comment by muser1492** [comment] 2023-08-06 16:59
Will OAuth 1.0a and Basic Authorization be supported?

**Comment by helloanoop** [comment] 2023-09-25 00:28
Auth is a key feature that is remaining to be implemented. I will be spending some time this week to get this completed.

**Comment by markwimpory** [comment] 2023-09-28 07:04
Im sure many many people are looking for a Postman alternative right now.  Bruno looks great to us we just need that auth stuff in particular oauth2 but im sure everyone has their favourite.  I will hold on making a decision until we hear more.

**Comment by ChristianSch** [comment] 2023-09-28 08:59
Just wanted to add my +1. We're exploring alternatives to Insomnia and oauth2 is a must for us to use our APIs properly.

**Comment by helloanoop** [comment] 2023-09-28 09:59
I will be releasing support for these Auth's tomorrow (Fri 29 Sep)
- Basic Auth
- Bearer Auth
- OAuth2.0

**Comment by Yang-Jace-Liu** [comment] 2023-09-29 04:35
Hello. Do you have any plan to implement cookies? i.e. set-cookies, cookies management, and automatically send the cookies under the same domain

**Comment by jthln** [comment] 2023-09-29 09:53
OAuth 1.0a support would be great, too.
Used by Magento 2, for example.
Since OAuth 2.0 is not backwards compatible to OAuth 1.0.

**Comment by helloanoop** [comment] 2023-09-29 20:26
Got busy with reviewing and merging PR's. Will be working over the weekend to get the auth support completed.

**Comment by DJphilomath** [comment] 2023-09-29 21:48
Will this also cover sending an auth bearer token when fetching a Graphql schema?

**Comment by helloanoop** [comment] 2023-10-02 00:02
> Hello. Do you have any plan to implement cookies? i.e. set-cookies, cookies management, and automatically send the cookies under the same domain

@yjlcoder Yes, we will support this. Its crucial.

> Will this also cover sending an auth bearer token when fetching a Graphql schema?

@DJphilomath  Yes, we will

> OAuth 1.0a support would be great, too.

@jthln Yes, We will support it after completing Oauth2.0

**Comment by ChadDa3mon** [comment] 2023-10-02 12:00
Just came here to say thanks a ton for this, I'm looking forward to trying it out. Seems like you're hard at work on the Auth issue, and that was my only big nag so far. I'm coming from Insomnia and I really like how they handled Authentication options via a dedicated tab. Being able to specify a username/password for basic auth, or various token options was quite helpful. 

I see you make mention of it in your documentation, but I can't see any easy way to implement this in the GUI.

**Comment by helloanoop** [comment] 2023-10-04 02:03
Support for Bearer and Basic Auth is now available in `v0.18.0`

Hoping to have Oauth 2.0 shipped in another 2 days time. I appreciate your patience.

**Comment by danielraab** [comment] 2023-10-04 06:28
Thanks for this cool new feature.
Now it would be perfect if the fields would be filled on an import (from e.g. Insomnia) :)

**Comment by fuxx** [comment] 2023-10-04 09:56
Cool! Thanks for the update @helloanoop - This will be a massive forward for bruno :)

**Comment by dahlsin** [comment] 2023-10-04 14:01
Hi! This was exactly what we were waiting for! It seems like it doesn't work to use collection variables for the auth values though, is that right or am I doing something wrong?
<img width="839" alt="auth_var_bruno" src="https://github.com/usebruno/bruno/assets/5725745/b26db1b1-4916-42ce-843e-78785b351d90">

**Comment by lared** [comment] 2023-10-04 16:19
@dahlsin tracked under #329

**Comment by Finkregh** [comment] 2023-10-05 07:04
Reading authentication from `~/.netrc` would be quite helpful as it allows sharing the config as well as usage of the same credentials by i.e. `curl -n`.

Thanks!

**Comment by rmueller83** [comment] 2023-10-05 13:04
Currently, the Auth credentials are stored in plain text in the bru file of the request. I do not think that this is a good idea, since projects are shared via Git.
The credentials should be encrypted or put into a separate file which can be excluded from git via `.gitignore`.

**Comment by helloanoop** [comment] 2023-10-05 13:07
@rmueller83 You'll be happy to see https://docs.usebruno.com/secrets-management/overview.html !

**Comment by helloanoop** [comment] 2023-10-05 14:26
Thank you @petoc for updating the insomnia importer to import basic and bearer auth strategies
PR: https://github.com/usebruno/bruno/pull/380

**Comment by olekyd** [comment] 2023-10-06 14:33
Hello, it would be nice to add AWS IAM auth method to the list

**Comment by bmrodgers148** [comment] 2023-10-06 15:04
Hi, @olekyd. I'm actually working on adding that feature now, as I need it for my work. I'll open a PR once I'm done testing it if someone else doesn't beat me to it. If you want to try it out, I just pushed the changes to my fork https://github.com/bmrodgers148/bruno

**Comment by helloanoop** [comment] 2023-10-06 15:24
@bmrodgers148 took a look at your changes. Love it 🔥
Looking forward to your PR..

So glad to see you take a stab at making changes in the Bru Lang Parser.

**Comment by helloanoop** [comment] 2023-10-09 03:33
I could not work on OAuth 2.0 auth as Ive been busy with adding Collection Level Headers, Auth, Scripts and Tests https://github.com/usebruno/bruno/issues/334 

Looking forward to get Oauth 2.0 done on priority in the next 2-3 days

@bmrodgers148 looking forward to your PR 😊 to add `AWS IAM` support.

**Comment by matbgn** [comment] 2023-10-09 05:01
Is there any chance to see Digest Auth implemented in Bruno?

**Comment by WtfJoke** [comment] 2023-10-10 21:19
Do you think it would make sense to split the issue? I could imagine it would be easier to track the different progress. 
For example I am mainly interested in OAuth 2.0 (and the progress is quite mixed, what I can totally understand but its a bit harder to follow) :)

**Comment by premeaswaran** [comment] 2023-10-16 07:44
Hey there @helloanoop , any update on this?

**Comment by Pessiun** [comment] 2023-10-26 14:05
When do we expect the JWT Bearer Auth to be in place?

**Comment by strattonjr** [comment] 2023-10-26 14:41
> Hi! This was exactly what we were waiting for! It seems like it doesn't work to use collection variables for the auth values though, is that right or am I doing something wrong? <img alt="auth_var_bruno" width="839" src="https://user-images.githubusercontent.com/5725745/272601589-b26db1b1-4916-42ce-843e-78785b351d90.png">

Try putting it in the body
![image](https://github.com/usebruno/bruno/assets/45074696/555bed46-468f-4ede-bc77-d08abe366940)

Then in Vars write the response to a new variable and reference that in your next call
![image](https://github.com/usebruno/bruno/assets/45074696/e2368633-e4af-45a5-99dd-2aa0503b5ef5)

**Comment by Pessiun** [comment] 2023-10-27 08:50
I managed to fix my JWT issue. It worked! Sometimes we need to apply try and error technique to succeed.

**Comment by markwimpory** [comment] 2023-10-31 10:48
Do we have an oauth2 update?  this is the only thing stopping us adopting Bruno right now.

**Comment by palhal** [comment] 2023-11-04 16:03
As others have mentioned, I would like to see a static API Key that can be included either as a header or in the query. I guess a screenshot from Postman will explain it:

![image](https://github.com/usebruno/bruno/assets/56862114/0ebc3c56-035e-4d5b-961c-bf172d86fddb)

My specific use case is the [Mapbox API](https://docs.mapbox.com/api/overview/#access-tokens-and-token-scopes). 

Btw, I just switched from Postman and I'm loving Bruno so far.

**Comment by gagan1393** [comment] 2023-11-07 16:32
Hi, Right now Oauth 2.0 is not available in bruno. Any idea when it is going to available? Or is there any alternative we can pass Oauth2.0 for a time being in bruno? 

Thanks!!

**Comment by mmornati** [comment] 2023-11-08 11:04
Acutually, for the oAuth2, `client_credential` is possible with a [simple script already shared on GitHub](https://github.com/usebruno/bruno/discussions/385#discussioncomment-7224068).
The real missing part is with other auth methods, even trying to simulate it, when you need to open a webpage to fillup the credentials, Bruno is not letting you a lot of latitude (I think it is not executing JS in the page preview, right?).

**Comment by gousse** [comment] 2023-11-09 14:42
Hi, for OAuth2.0, if the issue is the browser interaction, the easiest way is to use the device grant.
https://www.rfc-editor.org/rfc/rfc8628
it let you use any browser in another network/technical context to interact with the human user, while the "code on bruno side = device client" is just polling the token endpoint with a simple POST request. The ascii schem on rfc illustrate this.

**Comment by joe-gre** [comment] 2023-11-17 22:27
@helloanoop Any update on cookie support, including signed cookies? Our team uses this for authentication so its blocking us from adopting Bruno. I got parsing the cookie and setting it in a context variable in a post script working, but its not sending the cookie correctly. I hope this feature gets added so we can migrate. I've been waiting for an API client that integrates with git in this way for a while and I love the scripting support.

**Comment by joe-gre** [comment] 2023-11-17 22:55
I got cookie authentication working. It would be nice to have it as an out-of-the-box feature though. Here is what I did: https://github.com/usebruno/bruno/issues/968#issuecomment-1817220102

**Comment by osminogin** [comment] 2023-11-19 10:54
I would also like to suggest implementing an SSL/TLS client authentication method or any way to add and manage digital certificates in Bruno. This is a fairly popular way to authenticate clients to private APIs. 

This functionality is also available in Postman:
 
![certificates-add-client-cert-v10-16a](https://github.com/usebruno/bruno/assets/102770/b175116d-81d1-436c-bb41-067d5a15f87c)

**Comment by helloanoop** [comment] 2023-11-20 19:19
> I would also like to suggest implementing an SSL/TLS client authentication method or any way to add and manage digital certificates in Bruno. This is a fairly popular way to authenticate clients to private APIs.

@osminogin This is already available.

You can click on client certificates inside the collection settings (click on gear icon on top right corner once you open a collection)
![image](https://github.com/usebruno/bruno/assets/9350733/694add96-5097-424f-9892-53ffa66285f8)

**Comment by helloanoop** [comment] 2023-11-20 19:20
@yjlcoder @nomorsug @joe-gre 
Cookie support has landed in `v1.2.0`

If you encounter any issues or have additional feedback, please comment on #968

**Comment by helloanoop** [comment] 2023-11-20 19:23
This thread has become unmaintainable. I have created separate issues to track each kind of Auth. 

- [x] Basic Auth
- [x] Bearer Auth
- [x] Digest Auth
- [x] Cookie Auth - #968
- [x] AWS SigV4 Auth
- [ ] OAuth 2.0 #1003
- [ ] OAuth 1.0 #1004
- [ ] API Key based Auth #1005

Locking this thread. If you'd like an auth method to be supported, please create a new issue

PS: I appreciate the patience of folks waiting for OAuth 2.0.

**Closed** 2024-11-23 12:38 UTC
Labels: module-auth
