### ISSUE TITLE
Global variables (inter-collections variables)

### ISSUE THREAD

**Issue by electrotype** [usebruno/bruno#3207] opened 2024-09-26 23:25 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I have a collection dedicated to generating some authentication Access Tokens in a very specific way. In the "Post Response" script of a request in that collection, I set an "accessToken" variable:

`bru.setVar('accessToken', [taken from the response object]);`

I'd like to be able to then use this "{{accessToken}}" variable in _other_ collections!

In Postman, it's possible to use:

`postman.setGlobalVariable('accessToken', [taken from the response object]);`

... so the variable is available to all collections. 

Is there something similar in Bruno?

### Mockups or Images of the feature

![Screenshot_20240926_192436](https://github.com/user-attachments/assets/fc075fe0-f1e1-413b-af15-34814dcbae3a)

**Comment by helloanoop** [comment] 2024-10-13 02:58
Global Environments are now available in `v1.33.0` 🎉 

The api `bru.setGlobalEnvVar(key, value)` and `bru.getGlobalEnvVar(key)` are also supported

Also duplicate of #115

**Closed by helloanoop** 2024-10-13 02:58 UTC
Labels: enhancement
