### ISSUE TITLE
Support sub-environment

### ISSUE THREAD

**Issue by nofacer** [usebruno/bruno#2038] opened 2024-04-09 04:51 UTC
Currently it only supports global environment. It will be impossible to use same variable key like "host" with different value in each collection. The structure would be flat for now if each collection has multiple env collection such as <collection>-dev <collection>-prod

Is it possible to support it like insomnia does?

**Comment by sebimarkgraf** [comment] 2024-04-09 05:45
As far as I know, environments are scoped to collections.
As soon as you click on a request, the available environments change to the collection environment.

If you have the same variable multiple times in the same project and therefore Git Repository, you could just adjust host to be more specific.

**Comment by nofacer** [comment] 2024-04-11 06:22
@sebimarkgraf does it support base env and sub env like this? 
<img width="753" alt="image" src="https://github.com/usebruno/bruno/assets/8757916/5c204762-a509-4d38-b2f4-08521c5b71b6">
<img width="885" alt="image" src="https://github.com/usebruno/bruno/assets/8757916/78d73b79-9062-49a4-9a38-8abcb33b49db">

**Comment by edbrannin** [comment] 2024-06-24 20:20
(This is a duplicate of #292)

**Comment by sanjai0py** [comment] 2024-07-10 09:49
Closing this as duplicate of https://github.com/usebruno/bruno/issues/292. 

Please add a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to [issues you find important](https://github.com/usebruno/bruno/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Closed by sanjai0py** 2024-07-10 09:49 UTC
