### ISSUE TITLE
[BUG] Unable to create or import environments with names like DEV or QA. 

### ISSUE THREAD

**Issue by Sergi0Martin** [usebruno/bruno#1211] opened 2023-12-12 12:12 UTC
An error is thrown on create, rename or import the environment with name dev or qa. 

![image](https://github.com/usebruno/bruno/assets/16337833/250e00eb-c7be-4498-b839-87cc5093766c)

![image](https://github.com/usebruno/bruno/assets/16337833/8d15ebd4-a687-4810-94ab-0f73135377e1)

![image](https://github.com/usebruno/bruno/assets/16337833/de0b1ba7-4270-4ad6-8658-941800eb300e)

**Comment by bpoulaindev** [comment] 2023-12-12 14:52
@Sergi0Martin Isn't it because you already have environments with those names ? Haven't been able to reproduce your error without have duplicate names. We could correct "An error occured while created" btw.
<img width="151" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/46417399-e0c8-4ce2-b6b4-e5bfba3b2324">

**Comment by Sergi0Martin** [comment] 2023-12-12 15:00
> @Sergi0Martin Isn't it because you already have environments with those names ? Haven't been able to reproduce your error without have duplicate names. We could correct "An error occured while created" btw.
> <img width="151" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/46417399-e0c8-4ce2-b6b4-e5bfba3b2324">
> 

No, I have not environments with those names. What I did first was try to import from postman environment and the error was thrown, after that either create nor rename wasn't possible.
I downloaded the app yesterday so it should be the last version.

**Comment by bpoulaindev** [comment] 2023-12-12 15:13
Could you provide a screen record or the exact process you used to reproduce this issue ?
I tried importing a postman environment named DEV, renaming it to DEV2, renaming it back to DEV

**Comment by Sergi0Martin** [comment] 2023-12-13 14:38
@bpoulaindev 
Here is the video and the environmente file generated by postman, I removed some values for security reasons:
![Bruno_xFwqfwxi9e](https://github.com/usebruno/bruno/assets/16337833/cbd1da45-0ffb-434f-b083-fd97acf5ec6c)

[DEV.postman_environment.json](https://github.com/usebruno/bruno/files/13661850/DEV.postman_environment.json)

**Comment by bpoulaindev** [comment] 2023-12-13 15:12
I see what's happening, first time importing the env works fine but it doesn't appear in collection.
<img width="513" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/581afda2-451c-4a08-8624-ac0c7e60b34f">
The second import crashes because we're importing with the same name as the previous one, however the file still exists in the directory it's just unreadable, i'll see what i can do.
<img width="213" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/bcf9f36f-f4cd-4660-a251-54f69667a1c8">

**Comment by Sergi0Martin** [comment] 2023-12-13 15:27
I think it should not persist that file if the import failed. And some kind of error message in the devtool console would be also great.

Thanks @bpoulaindev.

**Comment by jiaming10** [comment] 2024-04-01 05:03
I will like to add on to this issue. I tried to create environment name `Localhost` or `localhost`, it faild with the error message `An error occurred while created the environment`, but there is no error message in the console.

I can't create it even though I don't have any environments.
![Screenshot 2024-04-01 at 12 56 07 PM](https://github.com/usebruno/bruno/assets/8718138/37a8f77d-6e80-4810-a931-17b59824c31d)

**Comment by bpoulaindev** [comment] 2024-04-02 07:20
@jiaming10 are you sure the environment isn't corrupted ? i can use the "localhost" name withut any issue, although it's with a very basic env file 
<img width="228" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/990bb28a-bafc-4bcd-a192-86dc8d415d62">

**Comment by jiaming10** [comment] 2024-04-03 02:25
> @jiaming10 are you sure the environment isn't corrupted ? i can use the "localhost" name withut any issue, although it's with a very basic env file <img alt="image" width="228" src="https://private-user-images.githubusercontent.com/64689165/318680252-990bb28a-bafc-4bcd-a192-86dc8d415d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTEwMzYsIm5iZiI6MTcxMjExMDczNiwicGF0aCI6Ii82NDY4OTE2NS8zMTg2ODAyNTItOTkwYmIyOGEtYmFmYy00YmNkLWExOTItODZkYzhkNDE1ZDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTU1NTFlNzgzY2EzOGE0YzQyNTMzYjdkMzRlN2U5NDQ0NTQyOGUwNjIyN2RlMDM3Mzk3NGE3ZjViNjlkY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cGxBMlwVKh4lXV9VSib2iZApDJ1iwx8J4aBzyfVgDoQ">

Sorry for the misunderstanding. I do have the envs in my folder, but it is not shown in Bruno client. So this leads to the confusion where:
1. Bruno unable to detect the `localhost` env in the folder.
2. Bruno unable to create `localhost`, because the env existed in the folder.

**Comment by jiaming10** [comment] 2024-04-03 03:04
@bpoulaindev you are right that the environment is corrupted. The imported Postman environment has variables with spaces in the name.

```
vars {
  User PasswordRecoveryToken: 
  User PasswordRecoveryTokenMobilePin: 
  User ChangeEmailTokenMobilePin: 
}
```

**Comment by sanjai0py** [comment] 2024-07-03 13:10
Closing the issue as it seems to be resolved. Please open a new issue if it isn't!

**Closed by sanjai0py** 2024-07-03 13:10 UTC
Labels: bug, help wanted
