### ISSUE TITLE
Update Bruno to latest version from GUI

### ISSUE THREAD

**Issue by hornta** [usebruno/bruno#2300] opened 2024-05-13 10:32 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I want to easily update Bruno from the program itself instead of having to download a new binary.

### Mockups or Images of the feature

-

**Comment by marfranke** [comment] 2024-05-14 07:54
Possible duplicate: https://github.com/usebruno/bruno/issues/103

**Comment by NiklasBr** [comment] 2024-05-14 08:30
Also mentioned here: https://github.com/usebruno/bruno/issues/1331#issuecomment-1878506060

**Comment by sanjai0py** [comment] 2024-06-14 09:11
Duplicate of #103

**Closed by sanjai0py** 2024-06-14 09:11 UTC
Labels: enhancement
