### ISSUE TITLE
Window for "Configure Environment" can't be scaled

### ISSUE THREAD

**Issue by uherbst** [usebruno/bruno#2732] opened 2024-07-31 11:04 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I'm happily running v1.22.0 on MacOS (installed from brew, if important).

If I need to configure environment variables, the window to do so (Click on : Environment/configure) can't be scaled / enlarged.
As a result, the variable names are not really readable - I can only see the first 16 characters.

Woraround for now is easy: Click in the name-field for the variable, there I can scroll to the end and the the whole variable name.
But this is not comfortable.

Any ideas now to change that ?

Thank you
Uli

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/50bcf783-ce5c-4791-a499-ec9d0ec5086d)

**Comment by sanjai0py** [comment] 2024-08-02 06:25
Closing this as a duplicate of https://github.com/usebruno/bruno/issues/1040. Thanks, @uherbst, for taking the time to create this descriptive issue. 

Please add a 👍 reaction to issue #1040 instead.

**Closed by sanjai0py** 2024-08-02 06:25 UTC
Labels: bug
