### ISSUE TITLE
Support multiple output file with single bruno cli say both json and junit same time

### ISSUE THREAD

**Issue by rshidling** [usebruno/bruno#2045] opened 2024-04-09 13:50 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bru CLI 1.3.0
Support multiple output file with single bruno cli say both json and junit same time

`bru run "GET configuration" -r --env ati002 --output res.json --output res1.json`

error when we use above example
```
Something went wrong
The "path" argument must be of type string. Received an instance of Array
```

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/8448089/6d192bdf-60e8-44e7-a096-ceaa26816cb4)

**Comment by sushmithasv** [comment] 2024-04-10 06:36
Have created an issue on passing multiple reporters in the command line https://github.com/usebruno/bruno/discussions/1068#discussioncomment-8718094

**Comment by marfranke** [comment] 2024-04-26 13:07
I think it would be useful too. However, contrary to https://github.com/usebruno/bruno/discussions/1068#discussioncomment-8718094, I suggest different Parameters:

- `bru run --junit junit.xml --json result.json --html result.html --text result.txt` support multiple reporters
- `bru run --output result.json --format json` legacy single output file (might already be used in scripts...)
- `bru run --stdout=json` choose your stdout format, possible values: json, junit, html, text (default), none
- Combining them should be possible: `bru run --output result.json --format json --junit junit.xml --stdout text`

PS: I think the label bug doesn't belong here, since the readme/--help doesn't even say multiple reporters are supported at the same time. Isn't it a feature request?

**Comment by rshidling** [comment] 2024-04-27 06:46
> I think it would be useful too. However, contrary to [#1068 (comment)](https://github.com/usebruno/bruno/discussions/1068#discussioncomment-8718094), I suggest different Parameters:
> 
> * `bru run --junit junit.xml --json result.json --html result.html --text result.txt` support multiple reporters
> * `bru run --output result.json --format json` legacy single output file (might already be used in scripts...)
> * `bru run --stdout=json` choose your stdout format, possible values: json, junit, html, text (default), none
> * Combining them should be possible: `bru run --output result.json --format json --junit junit.xml --stdout text`
> 
> PS: I think the label bug doesn't belong here, since the readme/--help doesn't even say multiple reporters are supported at the same time. Isn't it a feature request?

Yes, even I feel its feature request. Not sure how can Iabel this as feature.

**Comment by iamdavidfrancis** [comment] 2024-08-24 06:32
I threw together a PR that maintains back compat with the existing `--format` and `--output` but allows you to pass multiple `--format` options for using multiple reporters. 

You can set the reporter specific output using `--output.reporter`.

**Comment by helloanoop** [comment] 2024-08-26 06:24
Closing this issue as its a duplicate of #2918

**Closed by helloanoop** 2024-08-26 06:24 UTC
Labels: bug
