### ISSUE TITLE
Error while trying to export collection to Postman

### ISSUE THREAD

**Issue by VeselovAndrey** [usebruno/bruno#2040] opened 2024-04-09 07:15 UTC
I trying to export collection as Postman collection but getting following error (tried export different Bruno collections)
Bruno version: portable, Windows, 1.12.3
---
Oops! Something went wrong
TypeError: Cannot read properties of undefined (reading 'tests')

TypeError: Cannot read properties of undefined (reading 'tests')
    at generateEventSection (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:305839)
    at file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:307419
    at arrayMap (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:11:58444)
    at map (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:11:198057)
    at generateItemSection (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:307295)
    at exporters_postman_collection (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:307488)
    at onClick (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:308449)
    at Object.Nb (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:14966)
    at Tb (file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:15120)
    at file:///[path redacted]/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:33456

**Comment by KianLeong** [comment] 2024-04-09 09:11
This also happens in Bruno version:  Mac Apple Silicon 1.12.3

**Comment by sanjai0py** [comment] 2024-04-09 17:29
Duplicate of #1943

**Comment by helloanoop** [comment] 2024-04-10 15:45
This issue is fixed and will go out in the 1.13.0 release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.

**Closed by helloanoop** 2024-04-10 15:45 UTC
