### ISSUE TITLE
Replacement of collection variables not working in JSON body when host name includes an environment variable

### ISSUE THREAD

**Issue by rschwedasi** [usebruno/bruno#1483] opened 2024-01-30 14:05 UTC
Hey there,
we are experiencing some really weird behaviour with the replacement of collection variables in JSON POST bodies when the called URL does include variables aswell. Here a minimal example extracted from our project:

**Collections Script**

```
const moment = require('moment');

// dates
const firstOfNextMonth = moment().add(1, 'M').startOf('month')
bru.setVar("FIRST_NEXT_MONTH", firstOfNextMonth.format("YYYY-MM-DD"));
```

**Example 1 - POST {{MY_HOST}}/api/pricing**
```
{
    "persons": [
        {
            "id": 99,
            "roles": [
                {
                    "roleType": "APPLICANT",
                    "payment": {
                        "paymentPattern": "MONTHLY"
                    }
                }
            ]
        }
    ],
    "productBundle": {
        "insuranceDuration": {
            "from": "{{FIRST_NEXT_MONTH}}"
        }
    }
}
```

**Result**
This one results in the exact same request body. The variable does not get replaced with the actual value.

**Example 2 - POST {{MY_HOST}}/api/pricing**
If you cant't see the difference, I just swapped the properties `payment` and `roleType` in the JSON body of person[0].roles[0] 🤷‍♂️
```
{
    "persons": [
        {
            "id": 99,
            "roles": [
                {
                    "payment": {
                        "paymentPattern": "MONTHLY"
                    },
                    "roleType": "APPLICANT"
                }
            ]
        }
    ],
    "productBundle": {
        "insuranceDuration": {
            "from": "{{FIRST_NEXT_MONTH}}"
        }
    }
}
```
**Result**
The variable gets replaced with the appropriate value of the collection variable FIRST_NEXT_MONTH. 

**For Reproduction**
I attached my bruno collection, unfortunately the collection scripts don't get exported, therefore you have to add the first code block manually. 💾 [Download](https://github.com/usebruno/bruno/files/14099267/VariablesGoBrrrr.json)

**Comment by BlechaJosef** [comment] 2024-03-06 09:57
Hello,
I have the same problem.
Maybe it depends on whether the pre-request script sets the specified variable, if set var by the previous request its works

**Comment by sanjai0py** [comment] 2024-07-08 09:12
Hey @rschwedasi, I couldn't reproduce the bug in the latest version of Bruno [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2). I tried adding the script at both the collection level and the request level, and the request body values were interpolated as expected! Could you please verify this by trying out the latest version of Bruno?

**Comment by BlechaJosef** [comment] 2024-07-08 19:32
[Bugs.json](https://github.com/user-attachments/files/16133750/Bugs.json)
Hey @sanjai0py , You can try attached collection

**Comment by sanjai0py** [comment] 2024-07-23 05:19
Closing this issue as not reproducible.

https://github.com/user-attachments/assets/45949446-3560-4976-ac80-6c8e84fd041e

And @BlechaJosef, in the collection JSON you provided, the `pre-request` script is currently this: `bru.setVar("currentTime",moment());` which should be `bru.setVar("currentTime",moment().toString());` We can't assign objects to collection vars.

**Closed by sanjai0py** 2024-07-23 05:19 UTC

**Comment by BlechaJosef** [comment] 2024-07-23 06:26
@sanjai0py 
Thank you for the explanation.
I was confused that the console was returning the correct values `console.log("pre collection", bru.getVar("requestId"), bru.getVar("currentTime"))`
