### ISSUE TITLE
Extra Slash (`//`) in Generated API URL Causes Invalid Request

### ISSUE THREAD

**Issue by stephane-archer** [usebruno/bruno#3421] opened 2024-11-05 09:16 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

```
baseUrl: http://localhost:80/
API call is: {{baseUrl}}/transcode-video
```
the API call has been imported from an OpenAPI spec where each path must start with `/` to be valid according to the specification
the generated curl code is:
```
curl --request POST \
  --url http://localhost//transcode-video \
  --header 'content-type: multipart/form-data' \
  --form videoCodec=H.264 \
  --form height=500 \
  --form width=600 \
  --form originalVideoFile=@/Users/fractale/Desktop/proxy_test/a.mov
```
this request is not working because of the `//` in the URL

I'm not sure if the issue is in the code generator, not removing the `//` or the OpenAPI importer to import the `/` from the path or my `baseUrl` to include a `/` (it's the default value)

### Screenshots/Live demo link

<img width="1440" alt="Screenshot 2024-11-05 at 10 13 57" src="https://github.com/user-attachments/assets/c746fd3c-54b0-4134-9f33-85bc50305797">
<img width="1440" alt="Screenshot 2024-11-05 at 10 13 32" src="https://github.com/user-attachments/assets/3bdf8709-03a8-4c38-b2cc-cf25a8650e8c">
<img width="1440" alt="Screenshot 2024-11-05 at 10 13 47" src="https://github.com/user-attachments/assets/2b03421c-0930-4381-96fd-ffa262c02523">

**Comment by anusree-bruno** [comment] 2024-11-05 12:34
Hi @stephane-archer ,
It looks like the issue is due to a trailing / at the end of the base URL, causing the request to be http://localhost:80//transcode-video instead of http://localhost:80/transcode-video. The problem is with the openapi import, you can refer to issue #3116  for more details.

We'll work on a fix for this soon. In the meantime, you can manually update the baseUrl in your environment settings to resolve it.

**Comment by stephane-archer** [comment] 2024-11-05 13:04
Thanks for pointing out the issue
I will update my baseUrl

the openAPI import is not working properly but removing the trailing ˋ/ˋ automatically from baseUrl or "sanitize" the url by removing `//` by ˋ/` could be a good idea too?

What are your thoughts on this?

**Comment by anusree-bruno** [comment] 2024-11-23 12:40
Hi @stephane-archer this issue has been fixed by this [PR](https://github.com/usebruno/bruno/pull/3440/files).

I am closing this issue. Please feel free to reopen if the issue persists.

**Closed by anusree-bruno** 2024-11-23 12:40 UTC
Labels: bug
