### ISSUE TITLE
Variables doesn't work in multipart form body

### ISSUE THREAD

**Issue by Belozertsev-av** [usebruno/bruno#2662] opened 2024-07-18 11:28 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

If i enter values itself everything works fine, But if i trying to use variables get an error.
Windows 11 x64

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f76cd081-e57c-4ae1-8c7d-bc356f2a6aa3)

![image](https://github.com/user-attachments/assets/7d5ea666-b421-4ba9-bd69-9055faca3e7b)

![image](https://github.com/user-attachments/assets/e077b803-b780-41e8-8036-e903e1a6a4bd)

![image](https://github.com/user-attachments/assets/b719cbdb-0b57-43f5-be03-72237ba8f5cf)

**Comment by sanjai0py** [comment] 2024-07-18 12:10
I am sorry for the inconvenience caused by this bug, @Belozertsev-av. 

The issue you reported is a duplicate of https://github.com/usebruno/bruno/issues/352. There is already a pull request (https://github.com/usebruno/bruno/pull/2329) waiting to be merged. Thank you for your patience! 

Please add a 👍 reaction to the issue https://github.com/usebruno/bruno/issues/352 instead.

**Closed** 2024-07-19 06:33 UTC
Labels: bug
