### ISSUE TITLE
Value field need 'Mutil-line' option like insomnia.

### ISSUE THREAD

**Issue by ihorn** [usebruno/bruno#1190] opened 2023-12-09 15:41 UTC
![1](https://github.com/usebruno/bruno/assets/17956055/12316787-8354-4fd0-8906-b142cc33a852)
![2](https://github.com/usebruno/bruno/assets/17956055/8f4bdca0-ba3a-463d-8b61-972e2ab1647b)
![3](https://github.com/usebruno/bruno/assets/17956055/ebd7d9fd-b28a-4ab3-82e0-222b3451dc69)

**Comment by medsouz** [comment] 2023-12-13 16:02
Duplicate of #1138

**Comment by sanjai0py** [comment] 2024-07-03 12:44
Marking this issue as completed.

**Closed by sanjai0py** 2024-07-03 12:44 UTC
