### ISSUE TITLE
[Feature Request] Path parameter support (ex `/customer/:id`)

### ISSUE THREAD

**Issue by christopher-nash** [usebruno/bruno#1774] opened 2024-03-12 15:22 UTC
Postman supports setting path parameters using a `:value` syntax. See https://learning.postman.com/docs/sending-requests/create-requests/parameters/#send-request-parameters
> Path parameters form part of the request URL, and are referenced using placeholders preceded by `:` as in the following example: `/customer/:id`

I've used these _extensively_ in Postman which is making my switch to using Bruno quite difficult.

Please add support for these path variables to Bruno.

**Comment by wernsting** [comment] 2024-03-18 06:33
it would be nice but you can use path parameters by just inserting I have started using [Vars](https://docs.usebruno.com/scripting/vars.html) and just adding it under Pre request

**Comment by scott-t** [comment] 2024-03-27 02:54
Vars work but it's clunky (starts to 'pollute' the environment, and can be confusing if you also have actual vars that need changing in the request). 

Ideally both query and path params are visible on the same page so they can be edited together if both exist. Insomnia had a plugin that also gave this same functionality.

**Comment by hvitoi** [comment] 2024-03-31 18:02
For reference this feature has also been recently added to insomnia https://github.com/Kong/insomnia/pull/6994

**Comment by hvitoi** [comment] 2024-03-31 18:16
This is a duplicate of #852 by the way

**Closed** 2024-04-01 05:40 UTC
Labels: duplicate
