### ISSUE TITLE
Have an option to disable a request

### ISSUE THREAD

**Issue by FabKer** [usebruno/bruno#2695] opened 2024-07-24 09:26 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Is it possible to add a function disable/enable on a request?
This would make it possible to play a collection by excluding requests.
SoapUI allows this, and it's very practical.
If the request is disabled, she is not run.

### Mockups or Images of the feature

![Nouveau projet](https://github.com/user-attachments/assets/4c21c3a3-52f4-47ec-b1c7-b1846277b3c5)
![SCR-20240724-ft0](https://github.com/user-attachments/assets/9e09f438-4fd5-4e2e-8964-14c72922758c)

**Comment by sanjai0py** [comment] 2024-07-25 05:07
Duplicate of https://github.com/usebruno/bruno/issues/1039. Anyways, thanks @FabKer for taking the time to provide your valuable feature request!

Please add a 👍 reaction to issue https://github.com/usebruno/bruno/issues/1039 instead.

**Closed by sanjai0py** 2024-07-25 05:07 UTC
Labels: enhancement
