### ISSUE TITLE
Make send button bigger

### ISSUE THREAD

**Issue by Envoy49** [usebruno/bruno#3182] opened 2024-09-24 01:20 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Send button is super small and not comfortable to work with.
Make it larger and give some sort of colour to it instead of existing small arrow

### Mockups or Images of the feature

![image](https://github.com/user-attachments/assets/30f91c9b-a9dc-4bec-aa83-990d4494ae72)
just make it like a postman's SEND button with any colour u like, e.g. orange

**Comment by apoorvyadav1111** [comment] 2024-09-24 03:29
Hi, @helloanoop, Please assign this to me. I will raise a PR soon.

**Comment by sanjai0py** [comment] 2024-09-24 05:15
Hey @apoorvyadav1111, thank you for continuously expressing interest in contributing to Bruno. There is already a [PR](https://github.com/usebruno/bruno/pull/3141) that implements this feature. Your contribution there by reviewing it is greatly appreciated!

**Comment by sanjai0py** [comment] 2024-09-24 05:20
Thank you, @Envoy49, for taking the time to provide this valuable enhancement request. Currently, there is a [PR](https://github.com/usebruno/bruno/pull/3141) that implements your requested feature which hasn't been merged yet. Until then, we are tracking the feature in this [issue](https://github.com/usebruno/bruno/issues/2387). 

Please show your interest by adding a 👍 reaction to issue #2387.

**Comment by sanjai0py** [comment] 2024-09-24 05:20
Closing this issue as a duplicate of #2387!

**Closed by sanjai0py** 2024-09-24 05:20 UTC
Labels: enhancement

**Comment by Envoy49** [comment] 2024-10-18 05:09
sorry forgot to follow up on this.
looking forward to get this feature soon
