### ISSUE TITLE
How to handle Global variables in Bruno

### ISSUE THREAD

**Issue by AnanthaNagaraj** [usebruno/bruno#1509] opened 2024-02-02 05:16 UTC
### 
we are migrating our collections from post man to bruno, Few projects have global variables, how to use it ?
One work around : adding global variables values inside the env section.

**Comment by MagnusWestin** [comment] 2024-02-02 10:02
It would be nice to have "vars" in the collection also.

**Comment by antonfilichkin** [comment] 2024-02-05 20:33
We either need globals or sub-environments.

**Comment by bpoulaindev** [comment] 2024-03-14 15:31
If no one's working on this feature i can take it

**Comment by lizziemac** [comment] 2024-05-05 15:20
See https://github.com/usebruno/bruno/issues/115 for more discussion on the subject

**Comment by sanjai0py** [comment] 2024-07-08 09:31
Closing this as a duplicate of https://github.com/usebruno/bruno/issues/115.

**Closed by sanjai0py** 2024-07-08 09:31 UTC
Labels: enhancement

**Comment by Shudrum** [comment] 2024-09-03 10:14
Hello,

I think this issue was closed as a duplicate but is not a duplicate becuase environments and variables are different things.

Environments changes with the ... environments. Let's say we change an `API_KEY`, some configurations on the deployed APIs then yes : the environment configuration should change and make sense.

But, on our case for example, we have a variable like `userId` to use on many requests on different places depending on the requests: url parameter for some `GET`, body parameter for some `POST` and `PUT`, etc. This variable change frequently when our developpers tests and explore the API.

Currently there is two way to do that :

* Setting a `userId` variable on the `.env`, and when changing it: leaving bruno, updating the `.env` file then openning again Bruno and doing the request. Long and teddious.
* Manually changing the value of the `userId` on every requests, long, and prone to errors.

That is why environments !== variables. Having a simple variable UI per collection, easy to update from the requests maybe is going to be game changer. On our case I whould love to provide a Bruno repository for my team, but the experience is still not ready for an enterprise usage IMO.

In any case : great project and thank you!
