### ISSUE TITLE
[Bug] bru.setEnvVar unable to save env variable value

### ISSUE THREAD

**Issue by rahul-kumar-sdet** [usebruno/bruno#1065] opened 2023-11-27 10:33 UTC
Hi Folks,
I have written a  post-script for an API call to save a particular value from the response into a variable of the environment file.
The script written is as below, assuming the response has a json object named **someurl** which we want to set in bru environment variable. :--
const url = res.body.someurl;
bru.setEnvVar("XYZ_URL",URL);

After executing the collection containing these API calls via **bru run** I am not getting success response, on debug I noticed the environment variable named **XYZ_URL** is not getting the values , it remains empty.
<img width="850" alt="Env variable" src="https://github.com/usebruno/bruno/assets/60127632/a998dd87-9c95-4006-8732-e380fb13c636">

_Note: The same scripts works fine when I am running the API calls one by one manually._

**Comment by rareseu** [comment] 2023-11-28 19:32
Can confirm that bru.setEnvVar doesn't set the value. @rahul-kumar-sdet you can use setVar and getVar as Collection Vars, as I saw, they're temporary until I close Bruno.

**Comment by sojib-lowp** [comment] 2023-12-06 09:20
I can also confirm the output of @rareseu . Its really frustrating.

**Comment by helloanoop** [comment] 2023-12-06 10:05
@sojib-lowp Can you confirm which version of Bruno you are using?

This has been fixed in the latest version

**Comment by dcoxjr** [comment] 2023-12-13 20:35
I can also confirm this issue exists in v1.4

**Comment by helloanoop** [comment] 2023-12-14 18:46
@sojib-lowp @rahul-kumar-sdet @rareseu 

This should be working. I just checked on my machine on `v1.4.0` and it works.
Any chance you could share a screen recording of the issue ?

**Comment by sirmonopolio** [comment] 2024-01-24 22:56
I can confirm it as well
it works
<img width="587" alt="image" src="https://github.com/usebruno/bruno/assets/26074131/c6910a88-5700-4003-a7a9-68ab02e58b04">

**Comment by sanjai0py** [comment] 2024-07-03 05:51
Closing this issue because it appears to be resolved. Please open new issues for any related discussions.

**Closed by sanjai0py** 2024-07-03 05:51 UTC
