### ISSUE TITLE
Auto update or new version alert ?

### ISSUE THREAD

**Issue by bourpie** [usebruno/bruno#1611] opened 2024-02-16 15:36 UTC
Really appreciate all the the work being done with all the frequent updates!

Not an issue but more of a feature request. Would it be possible to add an auto update feature whenever Bruno has a new version or an alert telling us there's a new version update ?

Thanks a lot!

**Comment by smdedar** [comment] 2024-02-21 07:06
There is an old PR about this auto update

https://github.com/usebruno/bruno/pull/493

**Comment by sanjai0py** [comment] 2024-06-14 09:15
Duplicate of #103

**Closed by sanjai0py** 2024-06-14 09:15 UTC
Labels: enhancement
