### ISSUE TITLE
Support additional Menu option on open tabs

### ISSUE THREAD

**Issue by fintra** [usebruno/bruno#1632] opened 2024-02-20 02:42 UTC
Can you please enable additional menu on open tabs like we get on VS Code?
<img width="288" alt="Screenshot 2024-02-20 at 8 11 09 AM" src="https://github.com/usebruno/bruno/assets/142864596/ede337e7-d4f4-46c0-a13b-30990385b180">

**Comment by Phyziik** [comment] 2024-03-31 22:04
duplicate of #1093

**Closed** 2024-04-01 05:18 UTC
Labels: duplicate
