### ISSUE TITLE
Missing option to b64 encode client_id:secret for Get Access Token

### ISSUE THREAD

**Issue by binChris** [usebruno/bruno#3290] opened 2024-10-11 04:26 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am trying to get an Oauth cc access token for the Ebay API via Collection->Auth->Oauth2->Client_cred. This fails with a "invalid_client" toast message.

If I create my own request to get the token, I get the same error when I pass 
  `Authorization Basic {{client_id}}:{{client_secret}}`. 
Ebay wants id:secret to be base64 encoded - when I pass 
  `Authorization Basic {{client_id_secret_b64_encoded}}` 
the token is returned as expected.

So my assumption is, Get Access Token just passes the first form. An added option (checkbox) to base64 encode the id:secret would probably fix this.

N.b. it would be great to be able to "debug" the Get Access Token request / response to see what's actually going over the wire.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/b410d478-ccd9-426b-85a2-271e1e3f9a4b)

**Comment by pietrygamat** [comment] 2024-10-11 05:35
This is tracked in #2106.

**Comment by helloanoop** [comment] 2024-10-13 12:35
Closing this as this is a duplicate of #2106

**Closed by helloanoop** 2024-10-13 12:35 UTC
Labels: bug
