### ISSUE TITLE
Search Bar Encounters Counter

### ISSUE THREAD

**Issue by denismihaylovsap** [usebruno/bruno#2743] opened 2024-08-01 17:25 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

When you search in the Response Box there is no counter for how many elements were found and on which one you are. I am looking for something like Chrome's search, where you see how far you are to the end of the document.

### Mockups or Images of the feature

<img width="2358" alt="Screenshot 2024-08-01 at 20 25 43" src="https://github.com/user-attachments/assets/5fbfd22c-e221-42c8-af7c-9faddbd03b3b">

**Comment by sanjai0py** [comment] 2024-08-02 05:58
Duplicate of https://github.com/usebruno/bruno/issues/1432. Please add a 👍 reaction to issue https://github.com/usebruno/bruno/issues/1432 or comment in it instead.

**Closed by sanjai0py** 2024-08-02 05:58 UTC
Labels: enhancement
