### ISSUE TITLE
Mouseover-Preview for multiple placeholders without separator shows only the second variable

### ISSUE THREAD

**Issue by mirkogolze** [usebruno/bruno#246] opened 2023-09-29 09:40 UTC
![image](https://github.com/usebruno/bruno/assets/66121941/274e32e4-c9ce-43d4-8b30-204fe0e8a4e1)

The both variables `{{soapServer}}{{soapEndpoint}}` have different values.
They are used together without space or slash. When you hover then only the value of the second variable will be presented.
With separator ist works as expected.

**Comment by helloanoop** [comment] 2023-09-29 11:13
This is related to codemirror

Two key files affecting this behavior
Hover Tooltip:
https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/utils/codemirror/brunoVarInfo.js

Checking `{{var}}` blocks and highlight them green or red.
https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/utils/common/codemirror.js

**Comment by helloanoop** [comment] 2023-09-29 22:11
Closing this as this is the duplicate of https://github.com/usebruno/bruno/issues/113

@brahma-dev already has raised [PR](https://github.com/usebruno/bruno/pull/256/files) for the fix which will be released in the next outgoing build

**Closed by helloanoop** 2023-09-29 22:11 UTC
Labels: good first issue, help wanted

**Comment by helloanoop** [comment] 2023-09-30 22:36
@mirkogolze This has been fixed in `v0.16.5`
Thanks to @brahma-dev !

Closing this issue.
