### ISSUE TITLE
From cURL strips trailing slash from URL

### ISSUE THREAD

**Issue by jkjustjoshing** [usebruno/bruno#2658] opened 2024-07-17 20:01 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing a cURL command with a request URL ending in a trailing slash, the trailing slash gets stripped off

### Screenshots/Live demo link

https://github.com/user-attachments/assets/6d7856d6-d39e-4eff-81da-37f1a8c1a304

**Comment by sanjai0py** [comment] 2024-07-18 06:20
Closing this issue as a duplicate of https://github.com/usebruno/bruno/issues/2379.

Hey @jkjustjoshing, thanks for the detailed bug report. The demo video is creative, nonetheless.

Please react with a 👍 to issue https://github.com/usebruno/bruno/issues/2379 instead.

**Closed by sanjai0py** 2024-07-18 06:20 UTC
Labels: bug
