### ISSUE TITLE
[BUG] cryptic error message when accidentally leaving an empty Var

### ISSUE THREAD

**Issue by deanveloper** [usebruno/bruno#1186] opened 2023-12-07 23:13 UTC
I found out the actual reason for #362's "second issue" that persisted after disabling SSL, the one saying `Error invoking remote method 'send-http-request': Error: Key is required`.

I had a `Var` declared for the request, but it had no Name/Expr fields filled out. It took me quite a while to figure this out. Ideally these should either be ignored, or it should be a validation error that would be caught and highlight the field, similar to Script errors.

**Comment by Pithikos** [comment] 2024-01-02 13:48
Yes, this would be great to be fixed. For new comers it can be a turnoff, especially since there's pretty much nothing out there when googling the issue

**Comment by sanjai0py** [comment] 2024-07-03 12:35
Closing this is marked as resolved/cannot be reproduced in the latest version of Bruno [v1.20.0] (https://github.com/usebruno/bruno/releases/tag/v1.20.0). Please open a new issue if the bug still persists.

**Closed by sanjai0py** 2024-07-03 12:35 UTC
