### ISSUE TITLE
Make it possible to add folder-level configuration

### ISSUE THREAD

**Issue by esmiralha** [usebruno/bruno#1650] opened 2024-02-22 22:27 UTC
I need to add a pre-request script to many requests that are part of the same collection. I wish I could add the script to the folder containing the requests, so all of them would inherit the script .

**Comment by danielrehmann** [comment] 2024-02-27 14:02
I also would really like having a way to have finer grained structure of pre/post request scripts that allow a request hierarchy. Folders would be a nice approach.

**Comment by sanjai0py** [comment] 2024-07-08 10:46
The issue is similar to https://github.com/usebruno/bruno/issues/1310, which was released in version [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0) with the capability to specify Folder level `Headers`, `Script`, `Test`, and `Vars`. Please try the latest version of bruno.

**Closed** 2024-08-02 05:55 UTC

**Comment by cekeren** [comment] 2024-08-02 18:41
Has anyone here noticed that when you have "tests" filled out on a folder, they're not running via the bru cli? 

File Structure:
`.bruno/api-v2/$collectionFolder/` and then inside that I have 2 folders `pos_tests` and `neg_tests` for my positive and negative testing.

My negative test folder has a basic test to ensure `res.status` is not 200/201/202. 
```
test("Status: not 2xx", () => {
    expect(res.code).to.not.be.oneOf([200,201,202])
});
```

However, when I run my cli `bru run conversions/ -r --env local` the only neg_tests coming back with test results are those where I manually put tests in the individual .bru file to test my theory here. You can see in the screenshot below the 2 neg_tests where I manually configured a test, the following 3 calls with no test results (they're relying on the folder level test), and the first pos_test that ran with its tests (they're configured on the individual .bru file)
![image](https://github.com/user-attachments/assets/3623cb49-f9ca-482f-bc26-d5bf32cd2892)

**Comment by Its-treason** [comment] 2024-08-02 18:56
> Has anyone here noticed that when you have "tests" filled out on a folder, they're not running via the bru cli? 
> 
> File Structure:
> `.bruno/api-v2/$collectionFolder/` and then inside that I have 2 folders `pos_tests` and `neg_tests` for my positive and negative testing.
> 
> My negative test folder has a basic test to ensure `res.status` is not 200/201/202. 
> ```
> test("Status: not 2xx", () => {
>     expect(res.status).to.not.be.oneOf([200,201,202])
> });
> ```
> 
> However, when I run my cli `bru run conversions/ -r --env local` the only neg_tests coming back with test results are those where I manually put tests in the individual .bru file to test my theory here. You can see in the screenshot below the 2 neg_tests where I manually configured a test, the following 3 calls with no test results (they're relying on the folder level test), and the first pos_test that ran with its tests (they're configured on the individual .bru file)
> ![image](https://github.com/user-attachments/assets/3623cb49-f9ca-482f-bc26-d5bf32cd2892)

See https://github.com/usebruno/bruno/issues/2617 the Folder level settings seem to be missing from CLI

**Comment by cekeren** [comment] 2024-08-02 20:02
@Its-treason thank you! I missed this issue. I'll keep an eye on that. Appreciate it!
