### ISSUE TITLE
Data will be lost while same names in POST for "Form URL Encoded"

### ISSUE THREAD

**Issue by danshan** [usebruno/bruno#2192] opened 2024-04-28 08:22 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

v1.14.0 on Mac M1

When the POST type is `Form URL Encoded`, if there are parameters with the same name in the form, the data will be lost and only the last one will be retained.

### .bru file to reproduce the bug

[duplicated-form-params.bru.zip](https://github.com/usebruno/bruno/files/15141364/duplicated-form-params.bru.zip)

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/2695761/2e7b07b3-2ad2-4007-a88e-9d5d9602ee83)

**Comment by sanjai0py** [comment] 2024-08-29 10:55
Duplicate of #1320

**Closed by sanjai0py** 2024-08-29 10:55 UTC
Labels: bug

**Comment by sebabetz** [comment] 2024-10-19 16:01
I guess we have the same issue in multipart-form requests, as params with same names are overwritten by the last one instead all params being consolidated as an array.
https://github.com/usebruno/bruno/pull/2964 this fix only applies for form-url-encoded but should be applicable for multipart-form requests also.
