### ISSUE TITLE
Can it be installed with docker?

### ISSUE THREAD

**Issue by jearton** [usebruno/bruno#2728] opened 2024-07-31 05:32 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Docker installation

### Mockups or Images of the feature

Docker installation

**Comment by Its-treason** [comment] 2024-07-31 06:12
You can run the CLI inside Docker. There is an existing community maintained image: https://github.com/davidkarlsen/bruno-image

**Comment by sanjai0py** [comment] 2024-08-02 06:12
Closing this issue as a duplicate of #1415. Please react with a 👍 to issue #1415 instead.

**Closed by sanjai0py** 2024-08-02 06:12 UTC
Labels: enhancement
