### ISSUE TITLE
setEnvVar not persisted / Saved to environment file

### ISSUE THREAD

**Issue by lewisst** [usebruno/bruno#845] opened 2023-11-01 09:12 UTC
Using `bru.setEnvVar` the value is not saved to the environment file on disk

i.e create env file using ui

<img width="590" alt="image" src="https://github.com/usebruno/bruno/assets/12670242/d1690828-7c47-4323-bf65-fcdee3fc9c28">

File on disk:
```
vars {
  URL: https://jsonplaceholder.typicode.com/users/1
  name:
  email:
}
````

Call `{{URL}}`

post-request script
```
console.log("name: " + res.body.name);
console.log("email: " + res.body.email);


bru.setEnvVar("name", res.body.name);
bru.setEnvVar("email",res.body.email);
```

<img width="1634" alt="image" src="https://github.com/usebruno/bruno/assets/12670242/92b5eed7-64fa-4352-8c27-a691c5caaeba">

Env Fie in UI shows the populated values
<img width="588" alt="image" src="https://github.com/usebruno/bruno/assets/12670242/1333296d-3ffb-4093-aa27-a3f723f5ec4a">

however, the file on disk is not updated.
```
vars {
  URL: https://jsonplaceholder.typicode.com/users/1
  name:
  email:
}
```
If I add a new variable in the UI to the environment, the values then are saved.

[brunoSetEnvVar.zip](https://github.com/usebruno/bruno/files/13225300/brunoSetEnvVar.zip)

**Comment by vboctor** [comment] 2023-11-01 16:19
Should running API requests and associated scripts change the files that are checked into source control? I think that will be strange, since someone who just runs the API will now have changes into their repository.

**Comment by gjdonkers** [comment] 2024-01-11 14:53
I believe that both points are valid. @lewisst  do you have a work around for know? We have an API which needs information from the last call, this `ID` for example is used GET details later. When we restart Bruno (or the computer) this `ID` is gone, can we create a file `*.bru-local` for example with vars so we can store the values on the filesystem/repo but decide with `.gitignore` if this is checked in?

**Comment by sanjai0py** [comment] 2024-07-02 06:58
Closing this as a duplicate as the issue is being tracked here: https://github.com/usebruno/bruno/issues/2160. Please refer to this comment from @helloanoop https://github.com/usebruno/bruno/issues/2160#issuecomment-2197051417

**Closed by sanjai0py** 2024-07-02 06:58 UTC
