### ISSUE TITLE
Serve application updates trough the application with update options (Autodownload, auto update/install)

### ISSUE THREAD

**Issue by tester-at-bmi** [usebruno/bruno#2436] opened 2024-06-11 07:48 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I couId not find anything related to this. If this is a duplicate this feature request can be closed.

I would like to be able to update bruno facilitated by the application itself. Now you need to download a installer and install the application over and over again when a new update arrives.

### Mockups or Images of the feature

I think the issue described speaks for itself.

**Comment by sanjai0py** [comment] 2024-06-14 09:14
Duplicate of #103

**Closed by sanjai0py** 2024-06-14 09:14 UTC
Labels: enhancement
