### ISSUE TITLE
[Feature] Possibility to change the layout 

### ISSUE THREAD

**Issue by magicmarcy** [usebruno/bruno#1323] opened 2024-01-04 14:36 UTC
Hey guys,

at first: great work - I love bruno and use it every day <3

In my daily work, however, I noticed that the user experience could be a little better, especially with longer body or response data. Therefore, I would appreciate it if we could choose whether the response is displayed on the right (as it is now) or below the request.
Maybe it would also make sense if the response area could be undocked.

I look forward to an answer and see you then
Best regards,
Marcy

**Comment by Its-treason** [comment] 2024-01-06 16:04
I think this is a duplicate of #1041

**Comment by sanjai0py** [comment] 2024-07-05 06:15
Closing this as diplicate. 

Add a :+1: [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to [issues you find important](https://github.com/usebruno/bruno/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Closed by sanjai0py** 2024-07-05 06:15 UTC
