### ISSUE TITLE
Some of the editors make the layout scrollable and it's not needed

### ISSUE THREAD

**Issue by LeonardoMussato** [usebruno/bruno#911] opened 2023-11-07 11:59 UTC
I noticed that on the JSON editor when it opens it shifts the layout and the entire page becomes scrollable. This is caused by defined values similar to calc(100vh - 22px) and not using only height: 100% and display flex. I already created a pull request to fix this issue.

**Comment by martinsefcik** [comment] 2023-11-08 11:48
Probably it will be also resolved by PR #755 which handles more related issues with scrolling.

**Comment by vayalildanie** [comment] 2024-08-15 00:12
since #912 was closed this also should be as per: https://github.com/usebruno/bruno/pull/912#issuecomment-2268946402 probably

**Comment by sanjai0py** [comment] 2024-08-16 06:03
The issue is now closed as completed. Please make sure to use the [v1.25.0](https://github.com/usebruno/bruno/releases/tag/v1.25.0) version of Bruno.

**Closed by sanjai0py** 2024-08-16 06:03 UTC
Labels: bug
