### ISSUE TITLE
bruno - problem opening api collections

### ISSUE THREAD

**Issue by MontesaDave** [usebruno/bruno#1966] opened 2024-03-29 21:56 UTC
using Ubuntu Ubuntu 23.10 and installed bruno via snap 
( bruno snap install )

$ snap list bruno
Name   Version  Rev  Tracking       Publisher   Notes
bruno  1.12.3   31   latest/stable  helloanoop  -

start up bruno with no issues - initially all appears to be well.
when i go to open a collection things start to look strange.

any help greatly appreciated,
thanks dave

![Screenshot from 2024-03-29 17-46-42](https://github.com/usebruno/bruno/assets/32172990/b15b6269-5422-4efd-878a-492927596987)

**Comment by sanjai0py** [comment] 2024-04-01 10:58
This seems to be a duplicate of #1437

**Comment by dave-oswald** [comment] 2024-04-01 18:51
agreed - my apologies - I did not see that other ticket. 
( not sure what the process is for closing *this duplicate ticket* is ...
thanks dave.

**Closed** 2024-04-03 04:52 UTC
