### ISSUE TITLE
[BUG] Code generator

### ISSUE THREAD

**Issue by itchoust** [usebruno/bruno#1384] opened 2024-01-15 08:58 UTC
Hello,

I specified a basic authentication in the auth section of my request and i don't see Authorization header in the curl generated by Bruno.

Secondly, the environment variables are not replaced in the curl generated too.

Regards,

**Comment by Its-treason** [comment] 2024-01-15 17:53
I think this is a duplicate of #1208

**Comment by sanjai0py** [comment] 2024-07-03 12:58
Duplicate of #1208

**Closed by sanjai0py** 2024-07-03 12:58 UTC
