### ISSUE TITLE
[Feature Request] Run pre-request and post-response actions when fetching GQL schema

### ISSUE THREAD

**Issue by cwilper** [usebruno/bruno#704] opened 2023-10-20 17:28 UTC
# Why

In my environment, I need to digitally sign all request payloads, including GQL introspections. Since it's a very custom authentication scheme that is not in wide use, I thought it would be good to use a pre-request script for this. But I discovered that GQL schema fetching doesn't invoke pre-request scripts.

Although my use case doesn't call for it, I know Bruno has pre-request *and* post-response vars and scripts, so it seems like it would be good to also run those, and treat these requests just like any other request. Can anyone think of downsides to doing that?

# Related

Postman's GQL schema auto-fetch does not currently support running Pre-request scripts either, but people clearly want it:
*  https://github.com/postmanlabs/postman-app-support/issues/10957

**Comment by MatisseHack** [comment] 2024-03-19 04:32
I'm in the same boat! I handle authentication with a pre-request script, which isn't called when loading a GraphQL schema through introspection.

**Comment by jwsloan** [comment] 2024-05-06 21:31
I agree that this does not seem to work.

**Comment by Jackevansevo** [comment] 2024-05-15 15:12
I'm pretty sure there's been a regression since https://github.com/usebruno/bruno/pull/705 got merged.

I'm on v1.16.1 and currently affected by this.

**Closed** 2024-06-19 10:36 UTC

**Comment by helloanoop** [comment] 2024-06-19 10:37
I have merged the PR for the fix.
This is set to go out in the upcoming `v1.20.0` release
