### ISSUE TITLE
Cannot install windows edition of 1.12.3 due Windows defender

### ISSUE THREAD

**Issue by angelaatskandia** [usebruno/bruno#2020] opened 2024-04-05 12:28 UTC
Hi,
The installation of 1.12.3 .exe is stopped by the Windows Defender SmartScreen.
My guess is that it is due to the unknown publisher.
This is the first time I encounter the problem, for example 1.12.2 installation works fine.

![Bruno_windows_defender_12_3](https://github.com/usebruno/bruno/assets/166131467/d9f86bb7-017e-405d-be8e-032923a02a0b)

**Comment by sanjai0py** [comment] 2024-04-10 12:46
Duplicate of #1696

**Comment by helloanoop** [comment] 2024-04-15 08:06
@angelaatskandia 

This issue has been resolved in the latest release of v1.13.0
You can download the latest version from: https://www.usebruno.com/downloads

Please reopen the ticket if you are still facing issues.

**Closed by helloanoop** 2024-04-15 08:06 UTC

**Comment by XVII** [comment] 2025-03-26 04:15
@helloanoop , further to this, all recent app updates get blocked (assumedly due to age/prevalence).

Is it possible to submit them to https://www.microsoft.com/en-us/wdsi/filesubmission/ as a developer so we can help bypass "Microsoft Defender Smartscreen" errors?
