### ISSUE TITLE
[Bug] Proxy configuration mixed up with system config

### ISSUE THREAD

**Issue by samuel-deal-tisseo** [usebruno/bruno#1859] opened 2024-03-19 16:31 UTC
## Issue:

The proxy configuration get confused between my system proxy and an explicit proxy defined in Bruno.

## Example

Given the following configuration
* System proxy: `http://system.proxy:8080`
* Bruno proxy: `http://explicit.proxy:9000`

When I make a request to `http://neverssl.com`
I expect a call to `http://neverssl.com` via my the proxy `http://explicit.proxy:9000` 
But instead the call is to `http://neverssl.com:8080` (**wrong port**) via my the proxy `http://explicit.proxy:9000` 

## Environment: 
* Windows 10
* Http proxy
* Bruno 0.10 to 0.12

**Comment by samuel-deal-tisseo** [comment] 2024-03-20 08:13
It seems to be the same bug as #1448.
I'm sorry for duplication.

**Comment by sanjai0py** [comment] 2024-04-10 14:11
Duplicate of #1448

**Closed** 2024-07-09 08:14 UTC
