### ISSUE TITLE
OAuth2.0 Authorization code - Error on save - ValidationError: request.auth.oauth2.pkce

### ISSUE THREAD

**Issue by elsewhat** [usebruno/bruno#2080] opened 2024-04-15 06:20 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Saving of a a request with auth type OAuth 2.0 of grant type Authorization code fails with ValidationError: request.auth.oauth2.pkce.
If the checkbox "Use PKCE" is toggled on/off, the request is saved as expected. 

Stacktrace in devtool:
Uncaught (in promise) ValidationError: request.auth.oauth2.pkce must be defined
    at createError (_app-4a387ed14e1f2757.js:36:69067)
    at _app-4a387ed14e1f2757.js:36:69403

To reproduce:     
1. Create new request
2. Set Auth to Oatuh 2.0 and Grant type Authorization code
3. Fill in values for properties Callback URL, Authorization URL, Access Token URL, Client ID, Client Secret and Scope
4. Save request (this step fails) 

### .bru file to reproduce the bug

Not possible as issue is failure to save the request. See reproduction step in 

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/1133607/f1473d5e-c637-4648-8d73-9fd30e8b08c4)

**Comment by Its-treason** [comment] 2024-04-15 06:29
Duplicate of #2070

**Comment by sanjai0py** [comment] 2024-07-10 10:08
Closing this issue as a duplicate of https://github.com/usebruno/bruno/issues/2070.

**Closed by sanjai0py** 2024-07-10 10:08 UTC
Labels: bug
