### ISSUE TITLE
The function "search in reponse" is missing

### ISSUE THREAD

**Issue by yezhoujie** [usebruno/bruno#2599] opened 2024-07-10 01:21 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The function press ctrl+f to search in response is missing. This function exists in the previous version.

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/25244187/cf778bd8-ed91-4418-8400-f1b6d9c741f7)

**Comment by dwiyatci** [comment] 2024-07-10 17:41
It's not actually missing, it's just not shown 😕 ; I strongly believe it's related to https://github.com/usebruno/bruno/issues/2580

**Comment by sanjai0py** [comment] 2024-07-11 05:14
Duplicate of https://github.com/usebruno/bruno/issues/2580

**Closed by sanjai0py** 2024-07-11 05:14 UTC
Labels: bug
