### ISSUE TITLE
No "generate code" option in request menu

### ISSUE THREAD

**Issue by maurom** [usebruno/bruno#2984] opened 2024-08-30 15:40 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

First of all, thank you for your work on this useful offline API client.

I may be missing something, but in Bruno v1.27.0,  the "Generate code" item is not available in the request menu (Rename, Clone, Run, Delete are available, though). See attached `.bru` file for reference.

The collection is already saved, an environment is selected, and variables are available with proper values.

Apologies if this is due to something I've overlooked in the documentation.

### .bru file to reproduce the bug

```graphql
meta {
  name: SampleRequest
  type: graphql
  seq: 1
}

post {
  url: {{ROOT_URL}}/graphql
  body: graphql
  auth: none
}

headers {
  Authorization: JWT {{token}}
}

body:graphql {
  query GetUserInfo($id: Int!) {
    getUserInfo(id: $id) {
      name
      email
    }
  }
}

body:graphql:vars {
  {
      "id": 313
  }
}
```

### Screenshots/Live demo link

![bruno-no-generate-code-menu](https://github.com/user-attachments/assets/676a2e12-bc36-489a-985f-d4d79a9c7f2f)

**Comment by nikischin** [comment] 2024-08-30 15:52
This seems to be related to graphQL. Have you tried with other requests?

**Comment by berlingoqc** [comment] 2024-08-30 15:55
```
              {!isFolder && item.type === 'http-request' && (
                <div
                  className="dropdown-item"
                  onClick={(e) => {
                    handleGenerateCode(e);
                  }}
                >
                  Generate Code
                </div>
              )}
```

**Comment by berlingoqc** [comment] 2024-08-30 15:55
seem to only handle http-request by design

**Comment by berlingoqc** [comment] 2024-08-30 16:00
<img width="799" alt="Screenshot 2024-08-30 at 12 00 18 PM" src="https://github.com/user-attachments/assets/1891f292-f086-43fb-a8e6-9350b1efd2db">
 i remove the check but it need some work for it to work

**Comment by maurom** [comment] 2024-08-30 16:47
@nikischin Good catch. "Generate code" is available for standard HTTP / REST requests, indeed.

**Comment by maurom** [comment] 2024-09-04 14:43
See also:
- https://github.com/usebruno/bruno/issues/1031#issuecomment-1870248832
- https://github.com/usebruno/bruno/pull/1288

**Comment by anusree-bruno** [comment] 2024-11-08 14:02
Hi This has been fixed. Generate code option is available for GrapQl requests too.
![image](https://github.com/user-attachments/assets/25065a7f-6c1b-4330-81a5-a23d7370ec91)

I am closing this issue

**Closed by anusree-bruno** 2024-11-08 14:02 UTC
Labels: bug
