### ISSUE TITLE
[Feature] make link(s) in response clickable

### ISSUE THREAD

**Issue by jvsanten** [usebruno/bruno#1393] opened 2024-01-16 06:20 UTC
When dealing with apps that return links in the response (for example apps that use hal+json in their api) it would be nice to be able to click a link in the response to rapidly explore the API.

Ideally just (left) clicking the link would just follow the link (the same way it does in the HTML response previews), but would send along the same headers/auth info that was on the initial request. And right clicking (or some other secondary action) would pop up a dialogue to name a new request to be added to the collection for the new link (basically a clone of the original request with a new url and name).

A simple hal+json example:
```json
{
  "_links": {
    "self": {
      "href": "http://localhost:3210/"
    },
    "next": {
      "href": "http://localhost:3210/1"
    }
  },
  "page": "home"
}
```

A simple express server which can be used for testing:
```javascript
const express = require('express')
const app = express()
const port = 3210

app.get('/', (req, res) => {
        res.setHeader("content-type", "application/hal+json")
         res.send(JSON.stringify({
          "_links": {
                  self: {href: "http://localhost:3210/"},
                  next: {href: "http://localhost:3210/1"},
          },
                  page: "home"
  }))
})

app.get('/1', (req, res) => {
        res.setHeader("content-type", "application/hal+json")
        res.send(JSON.stringify({
          "_links": {
                  self: {href: "http://localhost:3210/1"},
                  previous: {href: "http://localhost:3210/"},
          },
                  page: "one"
  }))   
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

**Comment by bpoulaindev** [comment] 2024-01-16 08:20
Hi, there's a similar issue there : [issue #1029 ](https://github.com/usebruno/bruno/issues/1029)
I'm working on it alongside react-codemirror migration to have a better control over the IDE and its behaviour

**Comment by sanjai0py** [comment] 2024-07-05 07:22
Closing this as duplicate of https://github.com/usebruno/bruno/issues/1029

**Closed by sanjai0py** 2024-07-05 07:22 UTC
