### ISSUE TITLE
[Feature request] UI: tabs right click should open a context menu

### ISSUE THREAD

**Issue by BrandonGillis** [usebruno/bruno#1093] opened 2023-11-29 13:36 UTC
Hello, thanks for the bruno app, I'm loving it ! :)

### Feature request
Right now when doing a right-clik on an opened tab it does nothing.

It would be nice to have a context menu open like the following in vscode, with similar action to close tabs :

![image](https://github.com/usebruno/bruno/assets/27730101/71d2b5c6-5c3c-407d-a7a4-92192a473232)

**Comment by StonyTV** [comment] 2023-11-30 09:31
Hello @BrandonGillis 

I'm working on this feature.
![image](https://github.com/usebruno/bruno/assets/20698024/37f74c4f-a0d9-4a0c-a071-328a2c9b4ffc)

I start simple with the ability to create or clone a query.

The next step will be all deletion management. The difficulty is to manage successive modals if the tab has not been saved (draft mode).

I'm thinking of doing a PR this evening to initiate this.

**Comment by binaryfire** [comment] 2024-01-16 09:35
+1 for this. We really need a way to close all open tabs. A context menu would be the right place for that.

**Comment by Phyziik** [comment] 2024-03-31 21:55
Duplicate of #715

**Comment by sreelakshmi-bruno** [comment] 2024-11-08 15:12
Hi, this issue has been resolved in our latest release(1.34.2). Thanks!

**Closed by sreelakshmi-bruno** 2024-11-08 15:12 UTC
