### ISSUE TITLE
Weird Unmovable scroll bar in the tablist section

### ISSUE THREAD

**Issue by noornee** [usebruno/bruno#2293] opened 2024-05-11 20:43 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

There's a scrollbar-like bar appearing in my request tablist. (Check Screenshot)
noticed this too in v1.16.1

### Screenshots/Live demo link

![bruno-ui-bug](https://github.com/usebruno/bruno/assets/71889751/3192b0e2-2c4d-4c3e-9960-6e92aef3d3a5)

**Comment by busy-panda** [comment] 2024-05-13 13:09
On which OS, mac, windows of linux ?

**Comment by noornee** [comment] 2024-05-13 13:18
> On which OS, mac, windows or linux ?

Linux.

**Comment by busy-panda** [comment] 2024-05-13 13:25
has anyone else the problem ? 
i don't but i am on windows

**Comment by pietrygamat** [comment] 2024-05-13 17:42
> > On which OS, mac, windows or linux ?
> 
> Linux.

Looks like a custom theming problem. Are you using native or flatpak variant? I'd hope flatpak will not be affected regardless of what customisations are happening in the DE.

**Comment by noornee** [comment] 2024-05-13 18:13
> Looks like a custom DE theming problem 

wow, don't know why i didn't think it could be my theme. I'll try to remove it entirely to see if it's the cause. (my theme is Adwaita) 

> Are you using native or flatpak variant? 

Hyprland is my WM and I use the native variant of bruno or at least the one that's in the nixpkgs repository.

**Comment by Its-treason** [comment] 2024-05-13 21:26
I saw those scrollbars after upgrading Electron to version 29. They were caused by weird Bruno styling and the Chrome update.

Maybe the variant from NixOS also upgraded Electron.

I will try to look into it tomorrow.

**Comment by noornee** [comment] 2024-05-13 22:47
> I saw those scrollbars after upgrading Electron to version 29 on my Lazer fork. They were caused by weird Bruno styling and the Chrome update.

ahhh, I see.

> Maybe the variant from NixOS also upgraded Electron. @noornee Could you open Bruno's Chrome DevTools and check the Chrome / Electron version?

Sure. I just did and yep, you're right.
The electron version on my machine is v.29

![electron_version](https://github.com/usebruno/bruno/assets/71889751/296891b1-46d1-4f1a-b8e6-dadf7ea33fe4)


> I will try to look into it tomorrow.

Alrightt, Thank you!

**Comment by noornee** [comment] 2024-05-14 07:02
> I looked into the Nix build file: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix and the electron version in indeed overwritten:
> 
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix#L100-L112

Woww, pheww!. 
Guess I'm going to open an issue in the nixpkgs repository to tell them to pin a specific version of electron for bruno.

Thanks for narrowing out the source of this bug @Its-treason 🕵️

By chance, do you know the version of electron that bruno uses or atleast the last working electron version that didn't affect bruno's request tablist ui?

I modified the bruno package file and tried to build it locally using electron v28 on my machine but i had some errors that i couldn't stay to resolve, was running late to school. I'll look into it properly when i get home though. my best bet is that it's because i replaced every occurrence of the word `electron` with `electron_28` and it messed some things up

**Comment by busy-panda** [comment] 2024-05-14 09:21
I managed to reproduce it using the latest version of electron and I see how to fix it, I am making a PR

**Comment by noornee** [comment] 2024-05-14 09:53
> I managed to reproduce it using the latest version of electron and I see how to fix it, I am making a PR

that's awesome!

**Comment by busy-panda** [comment] 2024-05-14 10:44
Can I ask you @Its-treason to review my PR ?

**Comment by sanjai0py** [comment] 2024-08-27 11:01
Closing this issue as resolved. Please use the [v1.26.2](https://github.com/usebruno/bruno/releases/tag/v1.26.2) version of bruno which contains the fix.

**Closed by sanjai0py** 2024-08-27 11:01 UTC
Labels: bug
