### ISSUE TITLE
Bug: Default value for Bearer Token Auth is undefined

### ISSUE THREAD

**Issue by SoulKa** [usebruno/bruno#1532] opened 2024-02-07 09:42 UTC
When creating a new Request, the default value for the Bearer Auth is undefined:
![image](https://github.com/usebruno/bruno/assets/15342503/562e4930-5803-4f0a-a1e0-6b378b6a6948)

## Steps to reproduce:
1. Create new Request
2. Open the "Auth" tab
3. Select "Bearer Token" as auth type

## Expected behavior:
Empty input

**Comment by sanjai0py** [comment] 2024-07-01 07:23
The issue is being closed as it has already been resolved.

**Closed by sanjai0py** 2024-07-01 07:23 UTC
