### ISSUE TITLE
[Bug] Missing url prefix results in `Cannot read properties of undefined`

### ISSUE THREAD

**Issue by mppadding** [usebruno/bruno#387] opened 2023-10-05 12:05 UTC
When trying to send a request to `localhost:8000` without using a prefix such as `http://` or `https://` the following error pops up.
```
Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'headers')
```
<img width="421" alt="image" src="https://github.com/usebruno/bruno/assets/5224511/73d01024-9fe5-46c3-a269-f2307d22ad31">

It would be logical if bruno either:
- implicit prefix with `http://`
- implicit prefix with `https://`
- explicit message about the missing prefix

When generating code from this request I also get the following as raw HTTP request:
```
GET null HTTP/1.1
Content-Type: application/json
Host: 0.0.31.64
```

**Comment by benlloyd50** [comment] 2023-10-05 18:29
+1 to a configurable default like http:// or https:// for a collection and a explicit error message for this case. very easy to get tripped up on this when first using the app.

**Comment by eloo-abi** [comment] 2023-10-06 08:32
hi, 
i see the same error for different problems with a requests.. 
i guess right now the `Cannot read properties of undefined` is only a symptom of a different root cause.
For me it looks like the parsing of the bru file is not working because of some missing properties or wrong properties which results in `undefined` object.

Maybe it would be better to check if the file could be parsed anyway and check if the object is not `undefined` before trying to read the props.
And of course raise the parse error with a proper reason what causes the parsing to fail

**Comment by btecu** [comment] 2023-10-06 15:44
Running into the same, except I do have `https://` but I have a custom port and a special domain - looks like the error is not specific at all and is always displayed for any issue.

**Comment by btecu** [comment] 2023-10-06 17:50
Thanks, that fixed it in my case. Have I gotten an error about SSL I could have figure it out.

**Comment by edbrannin** [comment] 2023-10-07 20:47
Context for other people looking for this bug:

It seems like this happens when the request fails at a low level, like the target host not being found.

For example, I can "GET https://google.com" just fine, but I get this error when I `GET https://google.commmm`

**Comment by helloanoop** [comment] 2023-10-07 21:27
Have published a patch fix for this in`v0.21.1`

Hoping that this has also taken care of the issue @edbrannin mentioned

**Comment by eloo-abi** [comment] 2023-10-09 07:27
@helloanoop thanks for the fix.

can confirm in my case the generic error is gone.. 
but now i see a different one :P but thats another topic 👍

**Comment by anusree-bruno** [comment] 2024-11-21 14:46
Closing this issue as this has been fixed

**Closed by anusree-bruno** 2024-11-21 14:46 UTC
