### ISSUE TITLE
While importing from Postman, Request Body type is set as TEXT even though it is JSON in Postman

### ISSUE THREAD

**Issue by yuvanakannan** [usebruno/bruno#192] opened 2023-09-14 02:02 UTC

**Comment by yuvanakannan** [comment] 2023-09-15 01:14
Cannot reproduce. May be an adhoc case. Will reopen if encountered again

**Comment by helloanoop** [comment] 2023-09-15 05:26
Thanks @yuvanakannan !

**Comment by mirkogolze** [comment] 2023-09-20 06:26
I encountered the same problem. The problem is the export of postman. It seems to happen for older exports. Then sometimes the language is missing.

```
"request": {
	"method": "POST",
	"header": [
		{
			"key": "Content-Type",
			"value": "text/xml; charset=UTF-8"
		}
	],
	"body": {
		"mode": "raw",
		"raw": "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <soap:Body>\n  </soap:Body>\n</soap:Envelope>"
	}
}
```

**Comment by helloanoop** [comment] 2023-09-20 07:32
@mirkogolze Can you share a sample postman collection file so that I can reproduce this ?

**Comment by helloanoop** [comment] 2023-09-20 07:35
@mirkogolze I see that you already raised the PR for the fix.
I have merged it.

Many Thanks!

**Closed by helloanoop** 2023-09-20 07:35 UTC
