### ISSUE TITLE
Using dot (.) in variables names are recognized by the UI but not picked up when sending request

### ISSUE THREAD

**Issue by haneev** [usebruno/bruno#345] opened 2023-10-04 14:16 UTC
Really great tool! Keep up the good work. 

However I found a small bug 🙃

Some variables/placeholders are not picked up by the engine (but are recognized by the UI).

I tested the following:
- {{auth_token}} ✅
- {{auth-token}} ✅
- {{auth.token}} ⚠️

It does not work globally, so it does not work for url, body or headers.

**Comment by helloanoop** [comment] 2023-10-04 14:31
> Some variables/placeholders are not picked up by the engine (but are recognized by the UI).

Yes, this needs to be fixed. Codemirror shouldn't be highlighting this variable. The `.` may lead to unpredictable behaviour since it may interfere with the [handlebars templating logic](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/interpolate-vars.js#L31-L57)

**Comment by lared** [comment] 2023-10-04 18:56
@helloanoop is it just dots? Do we have some sort of a regex for valid variable names?

**Comment by razzivofficial** [comment] 2023-10-06 14:18
@helloanoop i tried to resolve this bug please review it if possible ! I am happy for any suggestions

**Comment by helloanoop** [comment] 2023-10-06 17:57
Hey @razzivofficial !

### Current and Expected Behaviour
Currently - env vars, request and other vars don't have a very strict validation for naming present. The expectation is that they should follow javascript's variable naming validation which is 

*Variable Names Must Start with a Letter, Underscore (_), or Dollar Sign ($)*

Unless there is a strong use-case (happy to change my mind if there is one) to name a var with other chars, bruno should use javascript's naming convention.

### Nested Vars
> Nested variables like {{auth.token}}

I have used the nested environments of insomnia in the past and like its benefits of have a base env and other env's extending the base env.

The reason why I went ahead with a simple key-val (like postman) was just because of its simplicity.

**Is there a plan to support nested environments ?**

Yes, In V2 - see [roadmap](https://github.com/usebruno/bruno/discussions/384)
Issue: https://github.com/usebruno/bruno/issues/292

### Changes need to nudge users that the name is invalid
To solve this, We need to show an error when people try to save an environment with an invalid name.
@razzivofficial Can you work on making these changes [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/Environments/EnvironmentSettings/EnvironmentList/EnvironmentDetails/EnvironmentVariables/index.js)

I am assuming we can make the table cell color red for invalid names, and disable the save button

![image](https://github.com/usebruno/bruno/assets/9350733/7609e93e-bfbc-4a80-a2c3-670e5cc87b82)

**Comment by martinsefcik** [comment] 2023-10-10 11:02
@helloanoop If you want to support some predefined/built-in variables for example as Postman do (https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) which start with `$` I would not allow to define such variables with dollar character at the beginning by user to distinguish between them.

**Comment by bpoulaindev** [comment] 2024-01-25 15:42
@helloanoop I see variables using "." have been brought back, however this causes somme issue in the code generator tab. {{baseUrl}} works fine in both requests and code generator tabs, but {{base.url}} only works in requests. What's the current situation regarding these changes ?

**Comment by helloanoop** [comment] 2024-09-04 19:02
The latest version of Bruno supports `.` in variable names.
Closing this issue.

If you are interested to see how Bruno handles interpolation, you can see the [examples here](https://github.com/usebruno/bruno/blob/main/packages/bruno-common/src/interpolate/index.spec.ts)

**Closed by helloanoop** 2024-09-04 19:02 UTC
Labels: bug, good first issue, help wanted
