### ISSUE TITLE
"About Bruno" issue

### ISSUE THREAD

**Issue by ivassemassayuki** [usebruno/bruno#1829] opened 2024-03-16 09:52 UTC
<img width="393" alt="Screenshot 2024-03-16 at 10 52 23" src="https://github.com/usebruno/bruno/assets/125784535/bc02ae74-748c-46e5-8331-d3d14ac59082">

**Comment by melroy89** [comment] 2024-03-17 00:27
It works for me.. So it might be a local Electron / HTML browser issue.. Very strange indeed.

**Comment by sanjai0py** [comment] 2024-07-09 07:10
Closing this as the issue doesn't seem to be reproducible in the latest version of Bruno. Please update to the latest version of Bruno [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2).

**Closed by sanjai0py** 2024-07-09 07:10 UTC
