### ISSUE TITLE
Error when click 'generate code' button

### ISSUE THREAD

**Issue by yezhoujie** [usebruno/bruno#2523] opened 2024-06-28 01:18 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Error page shows when click 'generate code' button

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/25244187/a86bf6cd-830a-418b-8dee-adefa786e9ba)

**Comment by jwetzell** [comment] 2024-06-28 14:46
duplicate of #2444 that was resolved by #2501

**Comment by jwetzell** [comment] 2024-07-01 18:02
this is resolved as of v1.20.0 @sanjai0py

**Comment by sanjai0py** [comment] 2024-07-02 04:55
Closing this as the issue has been fixed in [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).

**Closed by sanjai0py** 2024-07-02 04:55 UTC
Labels: bug
