### ISSUE TITLE
Request disappears from UI list when percent sign (%) in password field

### ISSUE THREAD

**Issue by PrimeF** [usebruno/bruno#1076] opened 2023-11-28 12:14 UTC
When the password field of the basic auth configuration contains a percent sign %, the request is not recognised and shown in the app.

Example request:
```
meta {
  name: ABC
  type: http
  seq: 1
}

get {
  url: https://abc.com/
  body: none
  auth: basic
}

auth:basic {
  username: USER
  password: A%
}
```

By removing the percent sign and restarting the app or moving the request's JSON file to another location and back the request pops up.

**Bruno version used**: v1.2.0

**Comment by bpoulaindev** [comment] 2023-12-07 15:15
Seems to be related to the bru-lang package, currently having a look and trying to identify the source of the problem

**Comment by likwidoxigen** [comment] 2024-06-05 14:25
Also unable to save when a Multipart Form param contains newlines. Example is [Oracle WebCenterRest](https://docs.oracle.com/en/cloud/saas/human-resources/24b/tutorial-hdl-rest/#Oracle-WebCenter-REST) where the sample is un-minified json.

**Comment by sanjai0py** [comment] 2024-07-05 06:59
Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1) 

https://github.com/usebruno/bruno/assets/84461672/6e4bda8b-0c26-4e4b-b7d3-6f5647295404

**Closed by sanjai0py** 2024-07-05 06:59 UTC
Labels: bug

**Comment by likwidoxigen** [comment] 2024-07-08 15:39
> Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1)


Should I open a new issue for the newlines in parameters preventing saves?

**Comment by sanjai0py** [comment] 2024-07-09 06:50
Hey @likwidoxigen, could you please check again? In the latest version of Bruno, multipart form data supports multiline values.

https://github.com/usebruno/bruno/assets/84461672/433c63d7-42f3-4764-acab-75664482b407

**Comment by helloanoop** [comment] 2025-03-12 23:07
@likwidoxigen If you are still facing issues, please raise a new issue.
