### ISSUE TITLE
[Feature Request] Import folder needs to be specified every time we import a new collection.

### ISSUE THREAD

**Issue by rahul-kumar-sdet** [usebruno/bruno#1044] opened 2023-11-24 05:30 UTC
The default import folder can be set by Bruno or once set can be taken for default. It is a repetitive task while migrating from another tool to bruno.

**Comment by mdabrowski-bluefin** [comment] 2023-12-10 20:59
Looks a duplicate of #636

**Comment by sanjai0py** [comment] 2024-07-01 11:11
Duplicate of #222

**Closed by sanjai0py** 2024-07-01 11:11 UTC
