### ISSUE TITLE
Can not install 1.12 due to firewall

### ISSUE THREAD

**Issue by kovacsdongo** [usebruno/bruno#1878] opened 2024-03-21 08:32 UTC
I would like to install the latest version, because i have a key for golden , but get a windows popup
"Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk."

**Comment by riesinger** [comment] 2024-03-21 09:41
This is a duplicate of https://github.com/usebruno/bruno/issues/1696

**Comment by sanjai0py** [comment] 2024-03-27 06:56
Closing this! Please open a new issue if you still face this issue.

**Comment by kovacsdongo** [comment] 2024-03-28 11:51
unfortunatelly, i get the same error with: bruno_1.12.3_x64_win, with portable too

**Comment by helloanoop** [comment] 2024-04-15 08:11
This issue has been resolved in the latest release of v1.13.0
You can download the latest version from: https://www.usebruno.com/downloads

Please reopen the ticket if you are still facing issues.

**Closed by helloanoop** 2024-04-15 08:11 UTC
