### ISSUE TITLE
[MacOS 14.5]Expand/Collapse is broken

### ISSUE THREAD

**Issue by psvmk** [usebruno/bruno#2610] opened 2024-07-10 14:09 UTC
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Expand/Collapse in left gutter sub panel is broken.

relevant info
```
MacOS 14.5
Bruno v1.20.3
electron | : 21.1.1
chrome | : 106.0.5249.103
node | : 16.16.0
v8 | : 10.6.194.17-electron.0
```

### Screenshots/Live demo link

<img width="1211" alt="left_gutter_expand_collapse_broken" src="https://github.com/usebruno/bruno/assets/88740682/dd3f732c-23ea-47cc-8db8-d3c04b3d9e4b">

**Comment by sfreeman422** [comment] 2024-07-10 14:13
Duplicate of #2580

**Closed** 2024-07-10 15:37 UTC
Labels: bug
