### ISSUE TITLE
Get request name in script

### ISSUE THREAD

**Issue by lrpe** [usebruno/bruno#2647] opened 2024-07-16 08:31 UTC
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I want to do something like the following in a pre request script:

`req.body.type = req.name`

Where req.name is the name of the request in the Bruno UI.

The reason is that I'm working with an API where all requests must specify the request name in the request body. All requests are made to the same URL. This would allow me to specify the request name once, in the Bruno UI, and have it automatically included in the request.

### Mockups or Images of the feature

This is what I need to do currently:
![image](https://github.com/user-attachments/assets/80ae35b9-abb2-4815-910e-e9515a69f5a5)

I want to be able to do this:
![image](https://github.com/user-attachments/assets/5c545067-12d9-4882-b8dc-7035bd6ea366)

**Comment by sanjai0py** [comment] 2024-07-16 08:57
Duplicate of https://github.com/usebruno/bruno/issues/987

**Comment by lrpe** [comment] 2024-07-16 09:04
Thanks @sanjai0py, I missed that when I searched. Closing this issue.

**Closed** 2024-07-16 09:03 UTC
Labels: enhancement

**Comment by sanjai0py** [comment] 2024-07-16 09:12
Please add a thumbs-up 👍 reaction to issue https://github.com/usebruno/bruno/issues/987 instead.
